### ISSUE TITLE
纯v6的网站无法访问

### ISSUE THREAD

**Issue by EdWard0x** [Aethersailor/Custom_OpenClash_Rules#102]
按照设置配置完成后，v6变得很奇怪
大陆v6地址检测可以检测到跟wan口一样的v6地址，不过会提示ipv4优先。我可以登录纯v6的服务器。但是无法ping通任何外部域名，比如google.com。同时将域名指向v6服务器，也是无法ping通。在v6服务器上搭建web服务也是无法通过浏览器访问。
这是什么原因？同时有解决方法吗？

**Comment by Aethersailor** [comment]
关闭 ipv6 ra 设置中的其他配置

**Comment by EdWard0x** [comment]
看了下，确实是v6设置有问题，感谢作者回复
