### ISSUE TITLE
OpenWrt-IPv6-设置方案，检测不通过，但是可以看IPV6直播源

### ISSUE THREAD

**Issue by li5bo5** [Aethersailor/Custom_OpenClash_Rules#104]
在设置过程中找不到IPV6源路由选项
![image](https://github.com/user-attachments/assets/77c13188-4351-440c-ad34-2efb8069b880)
![image](https://github.com/user-attachments/assets/97cea126-3d86-443a-addb-09a6435722b8)
![image](https://github.com/user-attachments/assets/f1b44125-7893-439c-a413-6d86ccc5f2a5)
![image](https://github.com/user-attachments/assets/dfbf6f0e-ab4f-4caa-8dbe-50c652798719)

**Comment by li5bo5** [comment]
<html>
<body>

固件版本 | ImmortalWrt 21.02-SNAPSHOT r20574-6cc28027be / LuCI openwrt-21.02 branch git-23.098.38725-847bd6b
-- | --



</body>
</html>

**Comment by li5bo5** [comment]
https://github.com/user-attachments/assets/549c5a4e-f5f3-4e19-8949-6496031f9923

这是设置的内容

**Comment by Aethersailor** [comment]
子设备没取得ipv6地址

**Comment by li5bo5** [comment]
> 子设备没取得ipv6地址
但是我的电视也是可以看直播源
这是什么原因呢？

**Comment by li5bo5** [comment]
> 子设备没取得ipv6地址

这、、怎么解决呢？

**Comment by li5bo5** [comment]
哦草、刚才更新了固件、好了一下。。。
后面我配置了OpenClash，之后又不行了（openclash处于关闭状态）

**Comment by li5bo5** [comment]
终极大招：重置固件。已解决
