### ISSUE TITLE
几条自用域名

### ISSUE THREAD

**Issue by paysenyu** [Aethersailor/Custom_OpenClash_Rules#107]
- DOMAIN-SUFFIX,nanhaicorp.com,DIRECT
- DOMAIN-SUFFIX,bdcb.cc,DIRECT
- DOMAIN-SUFFIX,jslife.net,DIRECT
- DOMAIN-SUFFIX,jslife.com.cn,DIRECT
- DOMAIN-SUFFIX,jackiewu.top,DIRECT
- DOMAIN-SUFFIX,myunraid.net,DIRECT
- DOMAIN-SUFFIX,unraid.net,DIRECT

麻烦有空添加一下哇，我不太会pr操作，只能发issue了，都是自用域名，但会被漏网之鱼代理

**Comment by Aethersailor** [comment]
请确认以上域名的解析结果是否为大陆IP

**Comment by smithereensarr** [comment]
你这也不说是什么网站，使用频率不高的都不会去加，不然无穷无尽，加太多还影响性能。

**Comment by paysenyu** [comment]
> 你这也不说是什么网站，使用频率不高的都不会去加，不然无穷无尽，加太多还影响性能。

好吧，不好意思啊

我以为只是正常的补充😂

前面几个都是国内一些企业的网站，基本是to B的，但也是国内域名和国内ip

那我自己手动添加吧，添麻烦了

**Comment by Aethersailor** [comment]
可以补充，但你要确定这些域名包含的二级域名对应的都是国内IP，并且也要说明对应的是什么网站    

结果如下
nanhaicorp.com  已添加，对应国内站点
bdcb.cc  不做添加，无法查找到相关站点信息
jslife.net  已添加，对应国内站点
jslife.com.cn  不做添加，CN域名默认绕过内核
jackiewu.top  不做添加，对应海外站点
myunraid.net  不做添加，对应海外站点
unraid.net  不做添加，对应海外站点

https://github.com/Aethersailor/Custom_OpenClash_Rules/commit/3bdaffa0ab449b84a5e1501d3666afc7c0111fed
已添加的冷门域名，会在 GeoSite 数据库收录后从本仓库移除。
