### ISSUE TITLE
VLESS/XTLS-RPRX-VISON/UDP线路被过滤了

### ISSUE THREAD

**Issue by amumufun** [Aethersailor/Custom_OpenClash_Rules#109]
服务端基于https://github.com/mack-a/v2ray-agent搭建的

**Comment by amumufun** [comment]
速度也被限制到40%以下

**Comment by Aethersailor** [comment]
啥意思？

**Comment by amumufun** [comment]
正常![image](https://github.com/user-attachments/assets/b7566283-dbb9-41a8-b3aa-3f93f4aae086)

不正常![image](https://github.com/user-attachments/assets/b6768c6f-05a1-4a1a-93fe-36126c6416ce)

**Comment by Aethersailor** [comment]
那这是openclash的问题，去隔壁问吧。。

**Comment by amumufun** [comment]
不使用订阅转换，节点是完整的，晚上看看是哪个步骤导致的
