### ISSUE TITLE
多条链接转换时部分节点可能无法使用

### ISSUE THREAD

**Issue by dbstd2333** [Aethersailor/Custom_OpenClash_Rules#11]
在openclash中，使用自建后端转换后，其中一家机场的tj节点全部失效，部分ss节点失效，使用其他规则就没有问题
![12cb0b966fd8910cc1047a5d7cca786](https://github.com/user-attachments/assets/c8713960-603e-440b-9ee6-10bc3e1719b5)

**Comment by dbstd2333** [comment]
在所有基于clash meta的代理软件上都无法识别另一家机场hk的tj节点

**Comment by CocoMilkMaster** [comment]
> 在所有基于clash meta的代理软件上都无法识别另一家机场hk的tj节点

开启[跳过证书验证],这个是openclash订阅转换的问题;
当订阅有规则的的时候,"证书验证"等规则会被op接受,订阅用于路由器等通用订阅时候,即使传递了规则,op还是会忽略,所以需要自己开启[跳过证书验证]

**Comment by dbstd2333** [comment]
> > 在所有基于clash meta的代理软件上都无法识别另一家机场hk的tj节点
> 
> 开启[跳过证书验证],这个是openclash订阅转换的问题; 当订阅有规则的的时候,"证书验证"等规则会被op接受,订阅用于路由器等通用订阅时候,即使传递了规则,op还是会忽略,所以需要自己开启[跳过证书验证]

got it，已解决，感谢

**Comment by weicaixian86** [comment]
> > 在所有基于clash meta的代理软件上都无法识别另一家机场hk的tj节点
> 
> 开启[跳过证书验证],这个是openclash订阅转换的问题; 当订阅有规则的的时候,"证书验证"等规则会被op接受,订阅用于路由器等通用订阅时候,即使传递了规则,op还是会忽略,所以需要自己开启[跳过证书验证]

在线订阅模板那里我已经开启跳过验证，仍然显示部分节点校验失败，我4个机场只有1个机场是出现这个情况，这个问题应该是机场自己的问题吧。

**Comment by mickeyman115** [comment]
> > > 在所有基于clash meta的代理软件上都无法识别另一家机场hk的tj节点
> > 
> > 
> > 开启[跳过证书验证],这个是openclash订阅转换的问题; 当订阅有规则的的时候,"证书验证"等规则会被op接受,订阅用于路由器等通用订阅时候,即使传递了规则,op还是会忽略,所以需要自己开启[跳过证书验证]
> 
> 在线订阅模板那里我已经开启跳过验证，仍然显示部分节点校验失败，我4个机场只有1个机场是出现这个情况，这个问题应该是机场自己的问题吧。

同样的问题

**Comment by weicaixian86** [comment]
您好，您发送的邮件已经收到。
