### ISSUE TITLE
hbo max 的app规则

### ISSUE THREAD

**Issue by JM-Heisenberg** [Aethersailor/Custom_OpenClash_Rules#110]
可以把这些也加到hbo的规则里吗，不然会跳掉国外媒体那里
  - DOMAIN,wmff.warnermediacdn.com
  - DOMAIN-SUFFIX,cinemax.com
  - DOMAIN-SUFFIX,discomax.com
  - DOMAIN-SUFFIX,h264.io
  - DOMAIN-SUFFIX,hbomax.com
  - DOMAIN-SUFFIX,hbomaxcdn.com
  - DOMAIN-SUFFIX,hbomaxdash.s.llnwi.net
  - DOMAIN-SUFFIX,hbonow.com
  - DOMAIN-SUFFIX,maxgo.com
  - PROCESS-NAME,com.hbo.hbonow

**Comment by Aethersailor** [comment]
https://github.com/blackmatrix7/ios_rule_script/issues/1421
去上游规则反馈
