### ISSUE TITLE
NAS的ipv6和openclash的DNSmasq冲突

### ISSUE THREAD

**Issue by robinzc2008** [Aethersailor/Custom_OpenClash_Rules#111]
已经按照wiki的方式成功设置好了openwrt主路由器（路由器桥接光猫、路由器拨号）

1.在开启openclash的DNSmasq时，局域网中，只有NAS的ipv6无法连通（但是连接路由器的PC已经分配到了公网ipv6，连通性测试正常）

2.尝试禁用openclash--插件设置--DNS设置（本地DNS劫持：选择【禁用】）
然后openclash不起作用，但是NAS的ipv6已连通....

求教，openclash和NAS的使用这两者必然不能共存吗？（规划把NAS作为本地服务器，NAS上部署了docker容器，也开通了DDNS，想用外网实现服务器的外网访问和管理）

**Comment by Aethersailor** [comment]
这个我也不太了解，建议到openclash仓库提问

**Comment by robinzc2008** [comment]
已经从openclash的github，wiki页面找到详细的配置教程了，按照教程设置好了，已经没有冲突了，感谢！


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月6日 22:54 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [Aethersailor/Custom_OpenClash_Rules] NAS的ipv6和openclash的DNSmasq冲突 (Issue #111) |

这个我也不太了解，建议到openclash仓库提问
