### ISSUE TITLE
转换模板的分组“节点选择”和分组内节点的疑问

### ISSUE THREAD

**Issue by zackzmai** [Aethersailor/Custom_OpenClash_Rules#112]
1、“节点选择”应该是定义了强制走代理的规则，同时这个分组被放到了下面大部分的分组里了，这样设置有什么特殊作用吗（就是比如Github分组里选中节点选择）？感觉是不是套娃套错了？
2、部分策略分组下面只含节点分组，另一部分策略分组下面除了节点分组还把所有节点引入了，是有意为之还是未清理完？（感觉除了Netflix等需要判断特定节点解锁之外的其他策略组都不需要引入所有节点）

**Comment by Aethersailor** [comment]
1. 这样设置是为了在某些情况下统一切换，比如只有一个节点的情况

2. 部分特定节点才能解锁的服务，比如奈飞，同时保留了地区分组和特定节点选择，这样使用全解锁的高端机场可以直接选择地区，使用垃圾机场可以配合解锁探测服务来选定当前可解锁的节点
其他不需要特定节点解锁的服务，比如Telegram，则只保留了地区分组和通用的节点选项（自动选择、节点选择等等）
