### ISSUE TITLE
raw.githubusercontent.com 在旁路由下解析不了

### ISSUE THREAD

**Issue by alex4814** [Aethersailor/Custom_OpenClash_Rules#116]
```powershell
> nslookup raw.githubusercontent.com
服务器:  UnKnown
Address:  240e:1c:200::1

非权威应答:
名称:    raw.githubusercontent.com
Addresses:  ::
          0.0.0.0
```
看起来是 DNS 污染了？我是在 Nameserver 里勾了第一项，填的运营商 DNS

**Comment by Aethersailor** [comment]
github地址应当返回fake-ip
说明你的openclash没有正确接管dns解析

**Comment by alex4814** [comment]
请问下应该怎么排查呢？
我用【插件设置】-【调试日志】测了【DNS测试（Clash查询结果）】，好像也是全0 IP。
```
Status: 0
TC: false
RD: true
RA: true
AD: false
CD: false

Question: 
  Name: raw.githubusercontent.com.
  Qtype: 1
  Qclass: 1

Answer: 
  TTL: 3340
  data: 0.0.0.0
  name: raw.githubusercontent.com.
  type: 1

Status: 0
TC: false
RD: true
RA: true
AD: false
CD: false

Question: 
  Name: raw.githubusercontent.com.
  Qtype: 28
  Qclass: 1

Answer: 
  TTL: 3340
  data: ::
  name: raw.githubusercontent.com.
  type: 28
```

**Comment by Aethersailor** [comment]
关闭dnsmasq设置中的dns劫持功能，openclash设置按照wiki里的来
下游设备的dns要设置为旁路由ip

**Comment by alex4814** [comment]
![image](https://github.com/user-attachments/assets/681ba5d3-ab5c-4970-a7e3-b1186f47fb87)
我看我的设置和wiki中的[关闭 Dnsmasq 自带的 DNS 重定向功能](https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%A1%88#%E5%85%B3%E9%97%AD-dnsmasq-%E8%87%AA%E5%B8%A6%E7%9A%84-dns-%E9%87%8D%E5%AE%9A%E5%90%91%E5%8A%9F%E8%83%BD)截图差别很大。
然后我看了下它的版本
```bash
root@OpenWrt:~# dnsmasq -v
Dnsmasq version 2.88  Copyright (c) 2000-2022 Simon Kelley
Compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua no-TFTP no-conntrack ipset nftset no-auth no-cryptohash no-DNSSEC loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
```
如果用配置文件的话，有对应的参数修改吗？

固件、参数等信息：
```
架构 | AArch64 Processor : Cortex-A53 * 4
固件版本 | OpenWrt R24.09.11 (by flippy) / LuCI Master (git-24.182.36151-66d29de)
内核版本 | 6.1.109-flippy-91+o
```

**Comment by Aethersailor** [comment]
> ![image](https://private-user-images.githubusercontent.com/963917/394302031-681ba5d3-ab5c-4970-a7e3-b1186f47fb87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NDA4MDIsIm5iZiI6MTczMzg0MDUwMiwicGF0aCI6Ii85NjM5MTcvMzk0MzAyMDMxLTY4MWJhNWQzLWFiNWMtNDk3MC1hN2UzLWIxMTg2ZjQ3ZmI4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxNDIxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDdiNzYxZThiMzZjOWM0OTdlM2E0ZTkwNzlhMGZkODE2NGUzMWEyODdjYTEwNTYyNjIyNzNjMTZjN2FmMTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TF42stCvFVeB1urlE_LEULENE1SeER6cq-t_QPEK3Uk) 我看我的设置和wiki中的[关闭 Dnsmasq 自带的 DNS 重定向功能](https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%A1%88#%E5%85%B3%E9%97%AD-dnsmasq-%E8%87%AA%E5%B8%A6%E7%9A%84-dns-%E9%87%8D%E5%AE%9A%E5%90%91%E5%8A%9F%E8%83%BD)截图差别很大。 然后我看了下它的版本
> 
> ```shell
> root@OpenWrt:~# dnsmasq -v
> Dnsmasq version 2.88  Copyright (c) 2000-2022 Simon Kelley
> Compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua no-TFTP no-conntrack ipset nftset no-auth no-cryptohash no-DNSSEC loop-detect inotify dumpfile
> 
> This software comes with ABSOLUTELY NO WARRANTY.
> Dnsmasq is free software, and you are welcome to redistribute it
> under the terms of the GNU General Public License, version 2 or 3.
> ```
> 
> 如果用配置文件的话，有对应的参数修改吗？
> 
> 固件、参数等信息：
> 
> ```
> 架构 | AArch64 Processor : Cortex-A53 * 4
> 固件版本 | OpenWrt R24.09.11 (by flippy) / LuCI Master (git-24.182.36151-66d29de)
> 内核版本 | 6.1.109-flippy-91+o
> ```

uci set dhcp.cfg01411c.dns_redirect='1'

240e:1c:200::1 这个地址是电信的DNS，你的设备的上游DNS应该是旁路由地址，IPv6配置错了
