### ISSUE TITLE
关于DNS设置的疑问

### ISSUE THREAD

**Issue by smithereensarr** [Aethersailor/Custom_OpenClash_Rules#117]
已逐句详细看了设置的教程，但还是对DNS设置这一块有疑问：

1. 教程里提到"然后在 OpenWrt 的首页查看并记录运营商下发给你的 DNS"，这个记下的DNS后文再没有提到过，也没有用上。
2. 教程中的截图勾选了【设置 OpenClash 覆写设置】-【自定义上游DNS服务器】（启用将覆盖配置文件内的设置，请先在下方配置好服务器）这个选项，但教程中又强调要把下方所有自定义的dns项的勾都取消勾选。那么勾选【自定义上游DNS服务器】的意义是什么？到底需不需要勾选，和“问题1”中提到的记下的运营商DNS有何关系？

感谢作者的付出，希望能得到解答。🌹

**Comment by Aethersailor** [comment]
1. 这里是我没改，实际上是查看是否取得运营商dns即可，因为后面的追加上游dns会用到wan口取得的运营商dns。wiki中内容已更正
2. 自定义上游DNS服务器 需要勾选，上面还有一个选项叫追加上游dns，启用了追加以后下面的第三方dns就不需要了。图文中都提到了这一点
