### ISSUE TITLE
关于DNS配置的疑问

### ISSUE THREAD

**Issue by smithereensarr** [Aethersailor/Custom_OpenClash_Rules#120]
教程中提到：“为什么要取消 Fallback 服务器？在取消 Fallback 服务器勾选的情况下，OpenClash 会把域名发送到远端的机场服务器上进行解析，只有这样才会根据不同区域的节点取得理论上的最佳解析结果”，为此我查阅了相关资料得到了一些解惑，同时又引发了两个新的问题。

1. 我查阅资料说，当不填写Fallback时，clash会根据域名分流规则，判断走直连还是代理。外网情况下会尝试使用当前分流规则的节点服务器进行DNS解析，但是我查到的资料是VMess协议或者还有别的我不知道的少数协议才支持DNS请求，例如Trojan节点本身不支持DNS请求，同时也极有可能不会转发DNS请求，导致走到nameserver的DNS解析，这样解出来的不是污染的ip吗？

2. 我严格按照教程配置，得到的配置文件中nameserver中除了有”dhcp://"pppoe-wan"，还有其他几个我不知道哪来的ip，这些ip是怎么来的呢？我查了其他配置，没有发现线索。

**Comment by Aethersailor** [comment]
1. 我没用过trojan，这个没关注过，如果确实如此可以自己勾选上fallback
2. . 勾选追加上游dns以后，你的nameserver是你的wan口dns和wan口网关
