### ISSUE TITLE
手机wifi不能完美解决。

### ISSUE THREAD

**Issue by jackieyiwu** [Aethersailor/Custom_OpenClash_Rules#125]
手机wifi无法避免的ipv6泄露，ipleak会显示本地局域我ip和ipv6地址，某些测试网站出现webrtc泄露，本人更换了手机浏览器，利用firefox的插件屏蔽了webrtc后，一切正常。

**Comment by Aethersailor** [comment]
主路由环境下 ios 下 safari 测试没任何问题，你的问题不是本项目设置导致的，建议自行查找原因，比如手机的ipv6 dns 是否正确设置为openwrt地址，浏览器是否有内置 dns
