### ISSUE TITLE
steam商店和下载分开

### ISSUE THREAD

**Issue by JiangChenrui** [Aethersailor/Custom_OpenClash_Rules#129]
能否把steam下载和steam商店分开，设置成两个选项，steam下载可以选择直连，steam商店走代理

**Comment by Aethersailor** [comment]
由于上游规则 Steam 部分没有区分商店和下载，且我暂时没有自行维护规则的计划，所以先保持现状吧

常用 Steam的话，建议使用 Watt toolkit，体验更佳

**Comment by JiangChenrui** [comment]
之前用Watt toolkit，昨天发现商店都连不上了，Watt toolkit出问题了

**Comment by bjl101501** [comment]
geosite更好用啊，`- GEOSITE,steam@cn,DIRECT`或者`- GEOSITE,category-games@cn,DIRECT`
