### ISSUE TITLE
DNS泄漏

### ISSUE THREAD

**Issue by imonior** [Aethersailor/Custom_OpenClash_Rules#131]
旁路使用（电信，主路华为光猫一体机，有ipv6），按教程设置，旁路上已关闭ipv6，dns服务检测（https://browserleaks.com/dns） 反馈全是北京的服务器，有ipv4的也有ipv6的，ipleak上的dns检测服务因维护中无法使用，所以没有检测结果，之前只用ipleak检测没发现dns泄漏，openclash最新版，没有升级。
firefox浏览器，已关闭安全DNS，且浏览器没有更换。

**Comment by imonior** [comment]
firefox浏览器，已关闭安全DNS，且浏览器没有更换。

**Comment by imonior** [comment]
> 旁路使用（电信，主路华为光猫一体机，有ipv6），按教程设置，旁路上已关闭ipv6，dns服务检测（[https://browserleaks.com/dns）反馈全是北京的服务器，有ipv4的也有ipv6的，ipleak上的dns检测服务因维护中无法使用，所以没有检测结果，之前只用ipleak检测没发现dns泄漏，openclash最新版，没有升级。](https://browserleaks.com/dns%EF%BC%89%E5%8F%8D%E9%A6%88%E5%85%A8%E6%98%AF%E5%8C%97%E4%BA%AC%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8%EF%BC%8C%E6%9C%89ipv4%E7%9A%84%E4%B9%9F%E6%9C%89ipv6%E7%9A%84%EF%BC%8Cipleak%E4%B8%8A%E7%9A%84dns%E6%A3%80%E6%B5%8B%E6%9C%8D%E5%8A%A1%E5%9B%A0%E7%BB%B4%E6%8A%A4%E4%B8%AD%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8%EF%BC%8C%E6%89%80%E4%BB%A5%E6%B2%A1%E6%9C%89%E6%A3%80%E6%B5%8B%E7%BB%93%E6%9E%9C%EF%BC%8C%E4%B9%8B%E5%89%8D%E5%8F%AA%E7%94%A8ipleak%E6%A3%80%E6%B5%8B%E6%B2%A1%E5%8F%91%E7%8E%B0dns%E6%B3%84%E6%BC%8F%EF%BC%8Copenclash%E6%9C%80%E6%96%B0%E7%89%88%EF%BC%8C%E6%B2%A1%E6%9C%89%E5%8D%87%E7%BA%A7%E3%80%82)

firefox浏览器，已关闭安全DNS，且浏览器没有更换。

**Comment by Aethersailor** [comment]
看wiki里的故障排除

**Comment by imonior** [comment]
已找到原因，ip v6没有关闭，自动获取到了主路由分配到ipv6地址和网关，关闭ip v6问题解决。
