### ISSUE TITLE
u2.dmhy.org未正确分流

### ISSUE THREAD

**Issue by KyonCN** [Aethersailor/Custom_OpenClash_Rules#132]
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list

这条规则引入了u2.dmhy.org直连（运行规则845行），但是dmhy被墙了，无法直接访问。
在其他规则里dmhy.org会走代理（运行规则12502行），所以share.dmhy.org倒是正确分流了。

**Comment by Aethersailor** [comment]
PT相关规则设置成直连是为了避免下载消耗节点流量
被墙了的话，那么消耗流量和被墙就必须二选一

**Comment by KyonCN** [comment]
> PT相关规则设置成直连是为了避免下载消耗节点流量 被墙了的话，那么消耗流量和被墙就必须二选一

tracker只是维护Seeder和Leecher列表吧，本身不存储文件，文件传输都是在用户间p2p，应该不存在从tracker服务器下载大文件走节点流量的问题。而且这个tracker连通性不是更应该是加强对象吗？

**Comment by Aethersailor** [comment]
已添加 dmhy.org 强制走代理
https://github.com/Aethersailor/Custom_OpenClash_Rules/commit/904e26906dc8a2df99a341a76b689ad460370f26
