### ISSUE TITLE
cloudflare.com和cursor.sh的国内直连设置

### ISSUE THREAD

**Issue by Tsqurt** [Aethersailor/Custom_OpenClash_Rules#134]
cloudflare、cursor在中国有ipv4和ipv6站点，且国内DNS服务器可以正确解析至国内的站点。以下是受到影响的域名：

```
cloudflare.com
cloudflarestorage.com
cursor.sh
cursor.com
```

这些域名错误地使用国外代理，让ollama服务和cursor服务在开启clash分流的情况下分配到“漏网之鱼”规则，进而通过代理连接至国外节点。

这些节点满足以下条件：
 - 这些域名不包含在 GEOSITE 的 [geolocation-cn](https://github.com/v2fly/domain-list-community/blob/master/data/geolocation-cn)中。
 - 域名的国内 DNS 解析结果为中国大陆境内 IP 地址。
 - 域名未能命中任何规则且错误分流至漏网之鱼策略组中。
 - ⚠这些域名没有在ICP/IP地址/域名信息备案管理系统中备案。运营它们的是获批在中国大陆运营的公司。

**Comment by Aethersailor** [comment]
已添加进直连规则
https://github.com/Aethersailor/Custom_OpenClash_Rules/commit/898d591b438e40e7b4519ba32eba8809651e0cb9

**Comment by 518512** [comment]
部分地区 cloudflare 还是无法快速访问，建议单独设置一个分类，用户选择是直连，还是用其他方式访问。

**Comment by Aethersailor** [comment]
已去除，直连会给部分用户造成困扰
