### ISSUE TITLE
ros主路由，op旁路由，按照教程一开启meta，就有问题

### ISSUE THREAD

**Issue by gygy** [Aethersailor/Custom_OpenClash_Rules#15]
ros主路由，opx86 原版系统旁路由，完全按照教程一开启meta，就有问题：
1、连接上，变慢。
2、经常连接不上gpt。
关掉：meta 马上正常。

**Comment by Aethersailor** [comment]
变慢是哪些域名访问变慢，国内还是国外，还是所有域名都变慢？

**Comment by gygy** [comment]
> 变慢是哪些域名访问变慢，国内还是国外，还是所有域名都变慢？

内外连接正常，但启动后，youtube在检查连接需要好长时间才正常。去掉meta则比较快。

**Comment by Aethersailor** [comment]
> > 变慢是哪些域名访问变慢，国内还是国外，还是所有域名都变慢？
> 
> 内外连接正常，但启动后，youtube在检查连接需要好长时间才正常。去掉meta则比较快。

建议去mihomo的仓库下提问

**Comment by sensen1** [comment]
我和你配置一样，我觉得有可能是你op里面 openclash版本的问题。

**Comment by gygy** [comment]
> 我和你配置一样，我觉得有可能是你op里面 openclash版本的问题。

原版及最新oc。开启meta，内外正常。但ytb手机会看不到视频图片。
