### ISSUE TITLE
催更lean的ipv6教程

### ISSUE THREAD

**Issue by ychang11** [Aethersailor/Custom_OpenClash_Rules#17]
从来没到会来GitHub催更。
希望大佬见谅。
由于我用的是sirpdboy的x86固件，也就是lean大的界面，目前一键开启ipv6之后，根据大佬的openclash设置，基本上是一切正常，ipv6测试网站都能通。
不过shield机顶盒的youtube无网络打不开，奇怪的是手机上的油管app跟其他需要科学的app都一切正常。
估计就是ipv6惹的祸？所以跪求大佬更新，小白才能依样画葫芦照抄作业。谢谢大佬。

**Comment by Aethersailor** [comment]
没道理手机能访问机顶盒不能访问，有可能机顶盒的油管app使用了内置dns
我目前没有设备使用 lean大的界面，所以一时半会不会去写教程，实在抱歉

**Comment by ychang11** [comment]
> 没道理手机能访问机顶盒不能访问，有可能机顶盒的油管app使用了内置dns 我目前没有设备使用 lean大的界面，所以一时半会不会去写教程，实在抱歉

昨晚后来查看了一下，手机打开油管，走的是ipv4的ip。不过机顶盒因为打开了ipv6，所以油管要走ipv6了，应该就是ipv6的设置不对所以过不去墙。
也不是特别着急。大佬有空有机会就更新下。谢谢

**Comment by Aethersailor** [comment]
> > 没道理手机能访问机顶盒不能访问，有可能机顶盒的油管app使用了内置dns 我目前没有设备使用 lean大的界面，所以一时半会不会去写教程，实在抱歉
> 
> 昨晚后来查看了一下，手机打开油管，走的是ipv4的ip。不过机顶盒因为打开了ipv6，所以油管要走ipv6了，应该就是ipv6的设置不对所以过不去墙。 也不是特别着急。大佬有空有机会就更新下。谢谢

lan 接口的 ipv6 和 ipv6 dhcp 中找到所有涉及 ipv6 dns 分配的功能，全部关闭，强制下游设备用 ipv4 dns 解析 ipv6 域名

**Comment by ychang11** [comment]
> > > 没道理手机能访问机顶盒不能访问，有可能机顶盒的油管app使用了内置dns 我目前没有设备使用 lean大的界面，所以一时半会不会去写教程，实在抱歉
> > 
> > 
> > 昨晚后来查看了一下，手机打开油管，走的是ipv4的ip。不过机顶盒因为打开了ipv6，所以油管要走ipv6了，应该就是ipv6的设置不对所以过不去墙。 也不是特别着急。大佬有空有机会就更新下。谢谢
> 
> lan 接口的 ipv6 和 ipv6 dhcp 中找到所有涉及 ipv6 dns 分配的功能，全部关闭，强制下游设备用 ipv4 dns 解析 ipv6 域名

![IMG_5801](https://github.com/user-attachments/assets/c3da8790-83a2-4952-b445-cee6757581fa)

刚才使试了把机顶盒的ipv6关闭，油管就可以用了。
大佬看看我这个lan口设置哪些要改。谢谢

**Comment by Aethersailor** [comment]
> > > > 没道理手机能访问机顶盒不能访问，有可能机顶盒的油管app使用了内置dns 我目前没有设备使用 lean大的界面，所以一时半会不会去写教程，实在抱歉
> 
> > > 
> 
> > > 
> 
> > > 昨晚后来查看了一下，手机打开油管，走的是ipv4的ip。不过机顶盒因为打开了ipv6，所以油管要走ipv6了，应该就是ipv6的设置不对所以过不去墙。 也不是特别着急。大佬有空有机会就更新下。谢谢
> 
> > 
> 
> > lan 接口的 ipv6 和 ipv6 dhcp 中找到所有涉及 ipv6 dns 分配的功能，全部关闭，强制下游设备用 ipv4 dns 解析 ipv6 域名
> 
> 
> 
> ![IMG_5801](https://github.com/user-attachments/assets/c3da8790-83a2-4952-b445-cee6757581fa)
> 
> 
> 
> 刚才使试了把机顶盒的ipv6关闭，油管就可以用了。
> 
> 大佬看看我这个lan口设置哪些要改。谢谢
> 
> 

NDP 代理禁用，通告的 DNS 服务器全部删除

**Comment by ychang11** [comment]
> > > > > 没道理手机能访问机顶盒不能访问，有可能机顶盒的油管app使用了内置dns 我目前没有设备使用 lean大的界面，所以一时半会不会去写教程，实在抱歉
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 昨晚后来查看了一下，手机打开油管，走的是ipv4的ip。不过机顶盒因为打开了ipv6，所以油管要走ipv6了，应该就是ipv6的设置不对所以过不去墙。 也不是特别着急。大佬有空有机会就更新下。谢谢
> > 
> > 
> > > 
> > 
> > 
> > > lan 接口的 ipv6 和 ipv6 dhcp 中找到所有涉及 ipv6 dns 分配的功能，全部关闭，强制下游设备用 ipv4 dns 解析 ipv6 域名
> > 
> > 
> > ![IMG_5801](https://private-user-images.githubusercontent.com/96138670/354639361-c3da8790-83a2-4952-b445-cee6757581fa.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTU1NjEsIm5iZiI6MTcyMjY5NTI2MSwicGF0aCI6Ii85NjEzODY3MC8zNTQ2MzkzNjEtYzNkYTg3OTAtODNhMi00OTUyLWI0NDUtY2VlNjc1NzU4MWZhLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxNDI3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGQzMDU0NmZkY2JmZjJiN2FhYjJkNjMyM2RlNjYwMGRiMjg1MDExMmIxOTMxNmI0ODAzY2Y2YTgyNTg2N2FkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P4Kc4JIU2GSQWGwf4w7yzqzk-EicwKuMLmBfjbGakZg)
> > 刚才使试了把机顶盒的ipv6关闭，油管就可以用了。
> > 大佬看看我这个lan口设置哪些要改。谢谢
> 
> NDP 代理禁用，通告的 DNS 服务器全部删除

刚才改了试试，油管可以用了，然后咪咕的电视app，变成代理出去了，看不了。又改回去了。还是耐心等大佬了。
谢谢
