### ISSUE TITLE
你好，发现了两个小问题，望大佬可以解惑

### ISSUE THREAD

**Issue by vbskycn** [Aethersailor/Custom_OpenClash_Rules#18]
大佬你好，用上了你的策略，真的非常好，比任何一种dns方案都要快
也没有泄漏
但有两个小问题
1.去广告，用了你的脚本，也看了规则，规则文件也拉到了tmp的目录，但是感觉是没有产生作用，完全拦截不到广告，两个规则都一样。

2.ipv6,我是爱快主路由+op,因为经常折腾op,如果只是op为主的话，那家里要经常断网了，所以只能双路，家人的设备不受影响。

  设置好了后，所有的设备都有公网 ipv6，但是测试会有dns泄漏
  
  _我看了下电脑的网关，ipv4的网关是旁路由，但是ipv6的网关指向了爱快，我猜这就是泄漏的原因之一吧。但是爱快里面的dhcp服务没有可以设置指定ipv6网关的地方呀

求大佬解惑

**Comment by vbskycn** [comment]
![image](https://github.com/user-attachments/assets/1035ec14-b202-4860-bd8b-85f02ff810ca)

经测试，在模板中加入了去广告规则，然后不绕过大陆，让流量经过clash，可以拦截广告

**Comment by vbskycn** [comment]
![image](https://github.com/user-attachments/assets/b2ab2292-116c-4747-99f9-3c181ac5a89a)

如果绕过大陆，用你的脚本去广告完全没有效果，就是这样子

**Comment by Aethersailor** [comment]
1.关于去广告问题  
检查 openclash 开发者选项中的广告拉取代码是否齐全  
`
curl -s https://anti-ad.net/anti-ad-for-dnsmasq.conf -o /tmp/dnsmasq.d/anti-ad-for-dnsmasq.conf
`
检查 openclash 启动后 /tmp/dnsmasq.d/anti-ad-for-dnsmasq.conf 文件是否存在，对照原始文件的体积和头尾内容确保广告过滤规则是完整的，如果文件不存在或者拉取不全，那么是网络问题，可以去 anti-ad 的仓库复制文件的raw地址自己添加 github 反代加速解决

我的脚本只是让 openclash 拉取规则给 dnsmasq ，如果 dnsmasq 正常加载规则的话，去广告不会有问题，前提是你的下游设备必须使用 OpenWrt 的 dnsmasq 作为上游 DNS。
你可以在 PC 和 OpenWrt 中分别 nslookup 一下广告域名看看是什么结果，需要在 openclash 提示“检测到 dnsmasq 正常启动，还原劫持规则”以后去广告才能生效，否则 dns 解析不会经过 dnsmasq  
正常情况下，广告域名应该是无法解析的  
![1](https://github.com/user-attachments/assets/73d6674a-d20c-4bdf-a0cd-8095fe30a7b2)
![2](https://github.com/user-attachments/assets/47cfa197-d715-45ba-be15-c927997d3e18)
在本仓库的设置方案中，dnsmasq 广告规则是和 openclash 绕过大陆规则采用了同样的实现方式（dnsmasq 启动时会加载 /tmp/dnsmasq.d/ 中的规则文件），如果绕过大陆功能正常工作，那么广告过滤必然也能正常工作。
至于为什么 dnsmasq 不能加载规则，这些异常不是我的设置方案导致的，无法知晓原因，无力解决，十分抱歉。

2. 旁路由 ipv6 我没折腾过，ikuai 我很久不用记不清设置了。建议找一下是否有设置可以修改 RA 标记的地方，让下游设备不要取得 ipv6 dns，只保留 ipv4 dns即可，强制所有域名解析请求通过旁路由，不会影响 ipv6 域名解析

**Comment by vbskycn** [comment]
感谢大佬这么详细的答疑。都是按照你的教程做的，/tmp/dnsmasq.d/anti-ad-for-dnsmasq.conf 文件 是正常生成的，大小也正常，打开看了一下，和浏览器打开内容相同。绕过大陆功能也正常，客户端dns设置也是旁路由，唯一不同的就是，在日志里面
2024-08-03 10:11:03 守护程序：检测到转发规则顺序错误，修改插件防火墙规则...
2024-08-03 10:10:03 提示：检测到 Dnsmasq 正常工作，还原防火墙 DNS 劫持规则...
2024-08-03 10:10:03 OpenClash 启动成功，请等待服务器上线！
2024-08-03 10:10:03 第九步: 添加计划任务,启动进程守护程序...
2024-08-03 10:10:03 第八步: 重启 Dnsmasq 程序...
2024-08-03 10:09:58 提示：开始添加自定义防火墙规则...
2024-08-03 10:09:57 提示：正在根据防火墙端口转发和防火墙通信规则添加端口绕过规则...
2024-08-03 10:09:57 提示：在 FAKE-IP 模式下绕过中国 IP 可能会导致 Dnsmasq 加载时间过长，暂时劫持 DNS 至内核直到 Dnsmasq 正常工作...
2024-08-03 10:09:57 提示：DNS 劫持模式为 Dnsmasq 转发...
2024-08-03 10:09:57 第七步: 设置防火墙规则...
2024-08-03 10:09:57 第六步: 等待主程序下载外部文件...
2024-08-03 10:09:54 第五步: 检查内核启动状态...
2024-08-03 10:09:53 配置文件【/etc/openclash/my dingyue.yaml】测试成功...
2024-08-03 10:09:51 启动前调用内核测试配置文件...
2024-08-03 10:09:51 提示：检测到配置了 Meta 内核专属功能，调用 Meta 内核启动...
2024-08-03 10:09:51 第四步: 启动主程序...
2024-08-03 10:09:50 提示：开始运行自定义覆写脚本...
2024-08-03 10:09:45 提示：您为 SOCKS5/HTTP(S) 代理设置的账户密码为【Clash:fqTkCuuM】
2024-08-03 10:09:42 第三步: 修改配置文件...
2024-08-03 10:09:42 提示：由于文件【 /etc/config/openclash 】被修改，暂停快速启动...
2024-08-03 10:09:42 第二步: 组件运行前检查...
2024-08-03 10:09:41 第一步: 获取配置...
2024-08-03 10:09:41 OpenClash 开始启动...

![image](https://github.com/user-attachments/assets/de72ad09-5412-4255-8eeb-25ccd9b603ed)


不知道是不是运行不正常，还是哪里设置的问题，还请大佬看看

**Comment by Aethersailor** [comment]
> 1.关于去广告问题  
> 
> 检查 openclash 开发者选项中的广告拉取代码是否齐全  
> 
> `
> 
> curl -s https://anti-ad.net/anti-ad-for-dnsmasq.conf -o /tmp/dnsmasq.d/anti-ad-for-dnsmasq.conf
> 
> `
> 
> 检查 openclash 启动后 /tmp/dnsmasq.d/anti-ad-for-dnsmasq.conf 文件是否存在，对照原始文件的体积和头尾内容确保广告过滤规则是完整的，如果文件不存在或者拉取不全，那么是网络问题，可以去 anti-ad 的仓库复制文件的raw地址自己添加 github 反代加速解决
> 
> 
> 
> 我的脚本只是让 openclash 拉取规则给 dnsmasq ，如果 dnsmasq 正常加载规则的话，去广告不会有问题，前提是你的下游设备必须使用 OpenWrt 的 dnsmasq 作为上游 DNS。
> 
> 你可以在 PC 和 OpenWrt 中分别 nslookup 一下广告域名看看是什么结果，需要在 openclash 提示“检测到 dnsmasq 正常启动，还原劫持规则”以后去广告才能生效，否则 dns 解析不会经过 dnsmasq  
> 
> 正常情况下，广告域名应该是无法解析的  
> 
> ![1](https://github.com/user-attachments/assets/73d6674a-d20c-4bdf-a0cd-8095fe30a7b2)
> 
> ![2](https://github.com/user-attachments/assets/47cfa197-d715-45ba-be15-c927997d3e18)
> 
> 在本仓库的设置方案中，dnsmasq 广告规则是和 openclash 绕过大陆规则采用了同样的实现方式（dnsmasq 启动时会加载 /tmp/dnsmasq.d/ 中的规则文件），如果绕过大陆功能正常工作，那么广告过滤必然也能正常工作。
> 
> 至于为什么 dnsmasq 不能加载规则，这些异常不是我的设置方案导致的，无法知晓原因，无力解决，十分抱歉。
> 
> 
> 
> 2. 旁路由 ipv6 我没折腾过，ikuai 我很久不用记不清设置了。建议找一下是否有设置可以修改 RA 标记的地方，让下游设备不要取得 ipv6 dns，只保留 ipv4 dns即可，强制所有域名解析请求通过旁路由，不会影响 ipv6 域名解析

在广告过滤规则中随便选一个域名，用 nslookup 检查解析结果

**Comment by Aethersailor** [comment]
> 感谢大佬这么详细的答疑。都是按照你的教程做的，/tmp/dnsmasq.d/anti-ad-for-dnsmasq.conf 文件 是正常生成的，大小也正常，打开看了一下，和浏览器打开内容相同。绕过大陆功能也正常，客户端dns设置也是旁路由，唯一不同的就是，在日志里面
> 
> 2024-08-03 10:11:03 守护程序：检测到转发规则顺序错误，修改插件防火墙规则...
> 
> 2024-08-03 10:10:03 提示：检测到 Dnsmasq 正常工作，还原防火墙 DNS 劫持规则...
> 
> 2024-08-03 10:10:03 OpenClash 启动成功，请等待服务器上线！
> 
> 2024-08-03 10:10:03 第九步: 添加计划任务,启动进程守护程序...
> 
> 2024-08-03 10:10:03 第八步: 重启 Dnsmasq 程序...
> 
> 2024-08-03 10:09:58 提示：开始添加自定义防火墙规则...
> 
> 2024-08-03 10:09:57 提示：正在根据防火墙端口转发和防火墙通信规则添加端口绕过规则...
> 
> 2024-08-03 10:09:57 提示：在 FAKE-IP 模式下绕过中国 IP 可能会导致 Dnsmasq 加载时间过长，暂时劫持 DNS 至内核直到 Dnsmasq 正常工作...
> 
> 2024-08-03 10:09:57 提示：DNS 劫持模式为 Dnsmasq 转发...
> 
> 2024-08-03 10:09:57 第七步: 设置防火墙规则...
> 
> 2024-08-03 10:09:57 第六步: 等待主程序下载外部文件...
> 
> 2024-08-03 10:09:54 第五步: 检查内核启动状态...
> 
> 2024-08-03 10:09:53 配置文件【/etc/openclash/my dingyue.yaml】测试成功...
> 
> 2024-08-03 10:09:51 启动前调用内核测试配置文件...
> 
> 2024-08-03 10:09:51 提示：检测到配置了 Meta 内核专属功能，调用 Meta 内核启动...
> 
> 2024-08-03 10:09:51 第四步: 启动主程序...
> 
> 2024-08-03 10:09:50 提示：开始运行自定义覆写脚本...
> 
> 2024-08-03 10:09:45 提示：您为 SOCKS5/HTTP(S) 代理设置的账户密码为【Clash:fqTkCuuM】
> 
> 2024-08-03 10:09:42 第三步: 修改配置文件...
> 
> 2024-08-03 10:09:42 提示：由于文件【 /etc/config/openclash 】被修改，暂停快速启动...
> 
> 2024-08-03 10:09:42 第二步: 组件运行前检查...
> 
> 2024-08-03 10:09:41 第一步: 获取配置...
> 
> 2024-08-03 10:09:41 OpenClash 开始启动...
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/de72ad09-5412-4255-8eeb-25ccd9b603ed)
> 
> 
> 
> 
> 
> 不知道是不是运行不正常，还是哪里设置的问题，还请大佬看看
> 
> 

在广告过滤规则中随便选一个域名，用 nslookup 检查解析结果

**Comment by Aethersailor** [comment]
不小心按错了删了一条评论，不好意思。。

**Comment by vbskycn** [comment]
最新测试，还是使用mosdns劫持53端口，设置本地电信dns为mosdns的上级。远程为 clash 127.0.0.1:7874
可以使用mosdns的广告过滤，dns缓存，以及更加灵活的其他设置。

多加一个mosdns所带来的影响完全可以忽略，感谢你的无私分享
