### ISSUE TITLE
能否将pt下载流量分流

### ISSUE THREAD

**Issue by AlbertMusk** [Aethersailor/Custom_OpenClash_Rules#2]
使用了几天发现非常不错，现在有一个问题就是pt下载和上传的流量全部走了match，能否添加一下没有的pt站点的分流规则，再就是pt下载和上传能否分流直连。

**Comment by AlbertMusk** [comment]
刚才尝试了一下，追加了几个规则，把tmdb，docker，github等的代理规则写在前面，后面跟上NAS的IP直连，目前来看一切正常。

**Comment by AlbertMusk** [comment]
请问大佬的规则里有没有针对cs2的游戏规则

**Comment by Aethersailor** [comment]
> 使用了几天发现非常不错，现在有一个问题就是pt下载和上传的流量全部走了match，能否添加一下没有的pt站点的分流规则，再就是pt下载和上传能否分流直连。

首先你找一个此类的上游规则碎片，然后用 openclash 的规则附加功能进行分流即可

**Comment by Aethersailor** [comment]
> 请问大佬的规则里有没有针对cs2的游戏规则

没有，目前没有添加任何的游戏规则。
你可以用 openclash 的规则附加功能单独添加游戏规则，在 openclash 的第三方规则管理中可以直接下载csgo的规则，或者自己用相应的工具抓取
以上操作和本项目的模板不冲突

**Comment by AlbertMusk** [comment]
感谢大佬解答

**Comment by ghost** [comment]
所以具体怎么分流能不能分享一下啊。我的下载也是走clash。谢谢

**Comment by Aethersailor** [comment]
> 所以具体怎么分流能不能分享一下啊。我的下载也是走clash。谢谢

要么自己附加规则碎片，要么屏蔽对应端口，我自己不用PT，所以没折腾这些
如果你用PT的话，就不适合用本项目的模板，因为本项目的模板是根据大陆和海外来进行分流的。使用PT的话更适合用gfw名单进行分流

**Comment by locoy-123** [comment]
覆写设置-规则设置-自定义规则 添加
DOMAIN-KEYWORD,tracker,DIRECT
DOMAIN-KEYWORD,announce.php?passkey=,DIRECT
DOMAIN-KEYWORD,torrent,DIRECT
DOMAIN-KEYWORD,peer_id=,DIRECT
DOMAIN-KEYWORD,info_hash,DIRECT
DOMAIN-KEYWORD,get_peers,DIRECT
DOMAIN-KEYWORD,find_node,DIRECT
DOMAIN-KEYWORD,BitTorrent,DIRECT
DOMAIN-KEYWORD,announce_peer,DIRECT
不知道这样是否可行

**Comment by LovinZTJ** [comment]
模板很好用  就是PT BT下载要走代理 不知道怎么写规则。

**Comment by Aethersailor** [comment]
增加了PT相关规则，可以更新一下订阅看看有没有改善

**Comment by Aethersailor** [comment]
> 覆写设置-规则设置-自定义规则 添加 DOMAIN-KEYWORD,tracker,DIRECT DOMAIN-KEYWORD,announce.php?passkey=,DIRECT DOMAIN-KEYWORD,torrent,DIRECT DOMAIN-KEYWORD,peer_id=,DIRECT DOMAIN-KEYWORD,info_hash,DIRECT DOMAIN-KEYWORD,get_peers,DIRECT DOMAIN-KEYWORD,find_node,DIRECT DOMAIN-KEYWORD,BitTorrent,DIRECT DOMAIN-KEYWORD,announce_peer,DIRECT 不知道这样是否可行

应该是不行的
只有第一条DOMAIN-KEYWORD,tracker可以生效

**Comment by lijunyi6259** [comment]
可以把这媒体配置进去吗？
https://raw.githubusercontent.com/77616211/puls/main/clasd/yinsshi.list

**Comment by Aethersailor** [comment]
> 可以把这媒体配置进去吗？
> 
> https://raw.githubusercontent.com/77616211/puls/main/clasd/yinsshi.list

个性化需求请 fork 本仓库后自行修改
