### ISSUE TITLE
大佬你好！想问下在不影响到你这个防止DNS泄露的配置效果为前提，如何正确开启opclash的白名单模式（让某些设备走代理）？

### ISSUE THREAD

**Issue by GCS3530** [Aethersailor/Custom_OpenClash_Rules#20]
大佬你好，我是小白一枚，教程非常的好，我也能跟着步骤一步一步来设置。就是想在不影响DNS泄露的前提下，开启opclash的白名单模式（也就是让某些设备走代理这样）。期待你的回复~

**Comment by Aethersailor** [comment]
更改 openclash 的 dns 设置中的劫持方式为防火墙劫持即可开启 openclash 的白名单模式
我不确定和我的其他设置是否兼容，自行测试
