### ISSUE TITLE
大佬，您好！新人求助

### ISSUE THREAD

**Issue by ColbyHe** [Aethersailor/Custom_OpenClash_Rules#21]
很高兴能够使用到如此优秀的配置。
但是，在使用中有小小的建议，现在向您提出，希望您这边看看是否可以采纳。

个人使用的节点没配置文件中那么复杂，请问是否有机会只展示原配置文件上的节点，在您的远程配置中移除多余的地区节点归纳？谢谢

**Comment by Aethersailor** [comment]
可以 fork 本仓库以后自行修改节点地区
