### ISSUE TITLE
节点部分校验失败

### ISSUE THREAD

**Issue by shadowfish07** [Aethersailor/Custom_OpenClash_Rules#24]
![image](https://github.com/user-attachments/assets/1e32cc93-3a4d-4ff6-b166-bd36ce4b5010)
不打开在线订阅转换是可以正常更新的，开启在线订阅转换就报这个错了，试了你提供的和自带的ACL4SSR 规则标准版都是一样的错，可能是什么原因导致？

**Comment by Aethersailor** [comment]
订阅设置中勾选跳过证书验证

**Comment by shadowfish07** [comment]
![image](https://github.com/user-attachments/assets/ed94d0da-31f4-4346-90dc-a024b2291ce6)
勾选了，报错一样，试了其他机场的订阅链接是可以的，难道是这家机场链接的问题？

**Comment by Aethersailor** [comment]
换别的订阅服务试试
另外订阅链接要填写v2rayN的订阅链接，不要填写clash订阅链接
另外请确定你的机场节点相关参数是 clash 支持的
此issue与本仓库无关，关闭了
