### ISSUE TITLE
根据最后的ipleak测试结果，还是存在很多国内甚至更具体的ip

### ISSUE THREAD

**Issue by user29957** [Aethersailor/Custom_OpenClash_Rules#27]
其实也没什么关系，开openclash上github更方便了，只是不知道其中原理，很好奇

**Comment by Aethersailor** [comment]
ipleak 出现国内 IP 说明设置不正确，请确保完全 100% 照抄教程设置。

**Comment by user29957** [comment]
> ipleak 出现国内 IP 说明设置不正确，请确保完全 100% 照抄教程设置。

谢谢作者的回复，无私的教程真的帮了大忙，我在白天重新设置检查下
