### ISSUE TITLE
捉个虫，当我漏网之鱼开启节点后，有些国内网站例如游民星空官网也会走代理，是否说明某些规则涵盖不全面

### ISSUE THREAD

**Issue by ytq77** [Aethersailor/Custom_OpenClash_Rules#29]
此外我不知道我是否应该开启跳过证书验证，有时有些常用节点会挂掉，存在一定时间间隔

**Comment by ghost** [comment]
先跟着教程设置，用起来没问题那就一直用。就像你说的证书跳过与否，如果开启更好使那就开。至于漏网之鱼，有些网站是会走代理，那就开启自定义规则就行了，至于游民星空，我刚测试，不走openclash更别说代理了。

**Comment by ytq77** [comment]
我这边还是走代理的。。所以我就加规则了：(
还在测试一些兼容之类的问题，谢谢回复

**Comment by ghost** [comment]
覆写设置→规则设置→自定义规则。里面有rules说明，直接添加你需要直连的规则即可。无需纠结~我已经稳定用了好几个月了！按照教程一步步设置就是了，不要跳着看，教程有些看似不重要的文字其实也是细节决定成败，忽略了可能就不起作用了或者出小问题的。

**Comment by ytq77** [comment]
确实有点小问题，打开某些网页的时候需要反应一会才可以打开，不然就提示连接重置之类的  大概要过一两分钟

**Comment by Aethersailor** [comment]
我每天都访问游民星空，我很确定，游民星空是不走代理的
访问它甚至根本不会经过内核，因为游民星空的地址包含在了 dnsmasq-china-list 中，并不是冷门网站，也不需要规则
检查你的 dnsmasq 是否正确加载了 dnsmasq-china-list，如果正常加载了 dnsmasq-china-list，那么游民星空域名的解析请求就不可能传递给 OpenClash
可以尝试把 OpenClash 和 Meta 内核都回退到 Master 版本，我看 OpenClash 的 issue 里有人反馈最新的 Dev 版本有类似问题

**Comment by wmgylc** [comment]
> 我每天都访问游民星空，我很确定，游民星空是不走代理的 访问它甚至根本不会经过内核，因为游民星空的地址包含在了 dnsmasq-china-list 中，并不是冷门网站，也不需要规则 检查你的 dnsmasq 是否正确加载了 dnsmasq-china-list，如果正常加载了 dnsmasq-china-list，那么游民星空域名的解析请求就不可能传递给 OpenClash 可以尝试把 OpenClash 和 Meta 内核都回退到 Master 版本，我看 OpenClash 的 issue 里有人反馈最新的 Dev 版本有类似问题

请问dnsmasq-china-list是默认存在还是需要自己手动配置？我是istoreos，似乎并没有加载这个组件。
然后确实包括游民星空这些都走clash

**Comment by Aethersailor** [comment]
> > 我每天都访问游民星空，我很确定，游民星空是不走代理的 访问它甚至根本不会经过内核，因为游民星空的地址包含在了 dnsmasq-china-list 中，并不是冷门网站，也不需要规则 检查你的 dnsmasq 是否正确加载了 dnsmasq-china-list，如果正常加载了 dnsmasq-china-list，那么游民星空域名的解析请求就不可能传递给 OpenClash 可以尝试把 OpenClash 和 Meta 内核都回退到 Master 版本，我看 OpenClash 的 issue 里有人反馈最新的 Dev 版本有类似问题
> 
> 请问dnsmasq-china-list是默认存在还是需要自己手动配置？我是istoreos，似乎并没有加载这个组件。 然后确实包括游民星空这些都走clash

如果游民星空走了 clash 那说明你的 openclash 的绕过大陆功能未正确生效，这个和规则没有关系的

dnsmasq-china-list 是 openclash 为 dnsmasq 拉取的规则
升级最新的 dev 版 openclash 试试，新版本换用了别的绕过方式，不再依赖 dnsmasq 去加载 dnsmasq-china-list

不过话说回来，istoreos下出问题的我遇到好几个了… 
我的设置方案本身并不会导致这些问题，至少在官方版本和 immortalwrt 下从来没遇到问题，毕竟绕过大陆功能是 openclash 自带的功能，和本仓库的规则模板覆盖程度并无关系，规则模板也不能影响一个访问一个域名是否经过 clash 内核，如果绕过大陆功能工作不正常，建议先从 openclash 之外的因素去排查
正常情况下，游民星空域名不会进入 openclash ，更不需要规则去覆盖了
至于为什么 openclash 在你那边工作不正常，我猜是固件的锅

**Comment by ytq77** [comment]
固件问题也不是没可能，，，遇到了一些dns污染的问题，这几天一直没时间排查。我用的immortalwrt23.05最新版本，今天再跟着你的教程过一遍流程看看有没有别的问题存在

**Comment by ghost** [comment]
我用的是esir的，作为参考~

**Comment by Aethersailor** [comment]
> 固件问题也不是没可能，，，遇到了一些dns污染的问题，这几天一直没时间排查。我用的immortalwrt23.05最新版本，今天再跟着你的教程过一遍流程看看有没有别的问题存在

我自用以及给亲朋好友配置的一共有五台设备用的 ImmortalWrt SNAPSHOT，配合 openclash dev版本没有任何问题
如果你要搭配其他的 DNS 插件，一定要先设置好确保 openclash 可以独立正常工作以后再修改配置配合其他插件工作

**Comment by ytq77** [comment]
目前我跟着走了一遍发现了之前一些忽略的点，可能导致前几次的各种问题。现在访问起来没有问题了！谢谢谢谢，下一步我准备搭配adguardhome使用

**Comment by wmgylc** [comment]
感谢，是内核问题，切换到dev解决
