### ISSUE TITLE
谷歌商店能打开无法更新

### ISSUE THREAD

**Issue by JayRose111** [Aethersailor/Custom_OpenClash_Rules#3]
大佬，按照教程配置完了手机谷歌商店无法更新，求解决

**Comment by Aethersailor** [comment]
nslookup services.googleapis.cn
检查一下google商店的域名解析返回是什么结果

**Comment by JayRose111** [comment]
服务器:  UnKnown
Address:  192.168.50.3

名称:    services.googleapis.cn
Address:  142.250.204.35

**Comment by JayRose111** [comment]
结果是这样 大佬

**Comment by Aethersailor** [comment]
> 服务器:  UnKnown
> 
> Address:  192.168.50.3
> 
> 
> 
> 名称:    services.googleapis.cn
> 
> Address:  142.250.204.35

解析结果不对
先检查设置和 Wiki 中的是否一致
然后重新更新一下订阅

**Comment by Aethersailor** [comment]
https://github.com/vernesong/OpenClash/discussions/3131
参考这个进行解决

**Comment by weicaixian86** [comment]
我的正常，自查一下吧。
