### ISSUE TITLE
开发者选项里的代码位置找不到 

### ISSUE THREAD

**Issue by derekling** [Aethersailor/Custom_OpenClash_Rules#32]
“按照图中内容，找到 Hash Demo 下的对应代码，取消注释并修改 true 为 false
ruby_edit "$CONFIG_FILE" "['experimental']" "{'sniff-tls-sni'=>false}"

但是开发者选项里并没有上述字段，怎么能显示出来呢

**Comment by Aethersailor** [comment]
代码是在“覆写设置”>“开发者选项”中的第27行，而不是“插件设置”>“开发者选项”。注意这是两个同名页面
