### ISSUE TITLE
选项有些不同，向大佬确认一下。

### ISSUE THREAD

**Issue by ghost** [Aethersailor/Custom_OpenClash_Rules#33]
![image](https://github.com/user-attachments/assets/4cf3cd19-8a65-4ea5-89c5-f1f336eed228)
这个地方跟Fake-IP-Filter有什么不同？这里你说可以填写DDNS，filter那里也可以填写DDNS，那这两个地方如何具体区别呢？

![image](https://github.com/user-attachments/assets/c0ceea4e-a600-4f49-b7cb-fdc32296935f)
Fake-IP-Filter下面有个模式，默认黑名单，没问题吧？

覆写设置里的规则设置，有些本来是国内的IP，但是出国了。我把这种网址都填入了自定义规则里。如果按照最上面的那个截图里说明的话，我这个自定义规则是不是就可以关闭并移动到「第二DNS服务器」选项里了？

以上，谢谢。

**Comment by Aethersailor** [comment]
第二 DNS 服务器：Dnsmasq 直接将域名交给你设置的服务器进行解析，绕过 Clash ，不受 Clash 影响
Fake-IP-Filter：相关域名不绕过 Clash 由 Clash 返回解析结果，只是不返回 Fake-IP 而是返回真实 IP，域名的解析结果受 Clash 规则影响。
两个地方都可以填你的 DDNS 域名，二选一即可

正常就是用黑名单模式，也就是 Fake-IP-Filter 中的域名才会返回 Fake-IP

如果你的第二 DNS 服务器设置的是国内 DNS 服务器，你可以把冷门的国内域名填进去来实现强制域名走国内 DNS 解析

**Comment by ghost** [comment]
多谢，完全明白了。
