### ISSUE TITLE
Steam下载覆盖不全

### ISSUE THREAD

**Issue by Kirie233** [Aethersailor/Custom_OpenClash_Rules#34]
![ZN_4 3HA70BLC W2 T S`Y4](https://github.com/user-attachments/assets/11911765-b4fb-41ec-9fa9-640c52578a46)
steam下载时有域名通过漏网之鱼走代理

**Comment by Aethersailor** [comment]
请登录国区
外服下载 CDN 暂时不做收录

**Comment by Aethersailor** [comment]
我这里测试没有问题，gstore.val.manlaxy.com 正确解析为国内 IP 地址并且绕过了 Clash 内核，规则不需要完善
![屏幕截图 2024-09-13 203722](https://github.com/user-attachments/assets/f15aa620-d27b-4c32-abbf-674b1cebb2fe)
请更新 OpenClash 和内核为 dev 版本，更新所有分流数据库，严格按照 wiki 进行设置，或者排查其他原因诸如固件自身问题等
