### ISSUE TITLE
dev版本0.46.028出现新选项“遵循规则”，勾选后原规则编译错误

### ISSUE THREAD

**Issue by sunpe7** [Aethersailor/Custom_OpenClash_Rules#35]
1、新增选项：覆写设置--DNS设置
<img width="426" alt="image" src="https://github.com/user-attachments/assets/f27c81fd-b020-4b45-b9b5-4219f57d07bc">

2、勾选后，下发配置后规则编译失败
<img width="499" alt="image" src="https://github.com/user-attachments/assets/259300a9-8f56-4c44-a871-6525e54f1691">

3、不勾选，规则可以编译成功，规则匹配目前正常。
<img width="513" alt="image" src="https://github.com/user-attachments/assets/da115f28-7030-41d2-8d4c-21038aa15a4b">

问题:目前不清楚这个选项的作用，请大佬说明一下用途

**Comment by sunpe7** [comment]
<img width="617" alt="image" src="https://github.com/user-attachments/assets/ca8e9bdf-9d4b-48d0-b506-6a4f2fc71de2">
暂时没看懂原因，勾选这个选项可以编译通过

**Comment by Aethersailor** [comment]
这个问题最好去 OpenClash 的仓库下提问，毕竟我不是作者。。

看了下，此处应该是对应旧版本的“Fallback DNS 代理组“功能
勾选后，因为配置文件中没有定义 Fallback DNS 所以订阅转换会失败。不勾选即可
