### ISSUE TITLE
用教程里面的订阅模板地址有的机场无法转换

### ISSUE THREAD

**Issue by zzstrive2007** [Aethersailor/Custom_OpenClash_Rules#36]
你好 我用教程里面的转换模板地址无法订阅机场，老是显示无法获取节点信息 尝试不用代理订阅，订阅失败。用自带的模板就没事。其他设置都是按教程里面设置的。谢谢

**Comment by Aethersailor** [comment]
更换别的订阅转换服务试试，有的订阅转换服务对模板中引用的规则有限制
教程中选用的 api.dler.io 无限制

**Comment by zzstrive2007** [comment]
好的 谢谢
