### ISSUE TITLE
寻求帮助：设置了某域名走直连的规则，但实际却用了IP走了兜底规则

### ISSUE THREAD

**Issue by cqjerry** [Aethersailor/Custom_OpenClash_Rules#37]
感谢楼主教程。

我碰到的问题是，ImmortalWrt主路由开启IPV6，套用你的ini配置，添加了一条自定义规则。设置了某一emby的域名走直连规则。
同一wifi环境下，安卓手机端使用了IP走了兜底规则用国外节点正常播放。谷歌电视盒子使用了域名规则无法正常播放。

**Comment by Aethersailor** [comment]
域名添加进第二dns服务中试试

**Comment by cqjerry** [comment]
试了关闭ipv6后正常了。
