### ISSUE TITLE
苹果快捷指令无法访问

### ISSUE THREAD

**Issue by gygy** [Aethersailor/Custom_OpenClash_Rules#39]
https://www.icloud.com/shortcuts/7473dbeef25c41a48126156adf908cd4

**Comment by Aethersailor** [comment]
我这里访问正常
![image](https://github.com/user-attachments/assets/498a9e85-1550-47fb-8dbd-66f3a00ca521)
icloud.com域名会根据对应的分组策略走直连或者你设置的节点
某些网址不能访问和本项目并无关系
