### ISSUE TITLE
教程里的图是无了吗？还是我的问题看不到了。

### ISSUE THREAD

**Issue by ghost** [Aethersailor/Custom_OpenClash_Rules#4]
https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B

比如这里的图无了

![image](https://github.com/Aethersailor/Custom_OpenClash_Rules/assets/98329765/48745638-8e95-4e00-a3a2-b57931cee370)

**Comment by Aethersailor** [comment]
是你的网络问题哦
建议参考 [Github520](https://github.com/521xueweihan/GitHub520) 项目的步骤修改本机 hosts 解决 github 图片不显示的问题

**Comment by ghost** [comment]
好的。谢谢！😄

**Comment by Ronchy2000** [comment]
请问是网络问题还是DNS设置问题？
校园网情况下，主路由配置下，启用上游DNS设置并取消勾选所有DNS服务，
github图片无法加载。

使用本地代理工具不会出现此问题。（已做验证 平台：win10/MacOS Sequoia 15.2
补充：Dnsmasq 自带的 DNS 重定向功能已关闭。
