### ISSUE TITLE
模板链接打不开了。。。

### ISSUE THREAD

**Issue by chouniu666** [Aethersailor/Custom_OpenClash_Rules#40]
模板链接打不开了。。。

https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/cfg/Custom_Clash.ini)/Aethersailor/Custom_OpenClash_Rules/main/cfg/Custom_Clash.ini

**Comment by Aethersailor** [comment]
你仔细看看你发的这个链接对嘛
