### ISSUE TITLE
配置建议

### ISSUE THREAD

**Issue by bdingtech** [Aethersailor/Custom_OpenClash_Rules#41]
在[OpenClash 设置教程](https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%95%99%E7%A8%8B)的「配置订阅」一节中，**建议打开「使用规则集」选项**。
![CleanShot 2024-09-24 at 13 26 33@2x](https://github.com/user-attachments/assets/324a89c6-c059-49b0-8c48-7e732ecf4df4)

**理由如下：**
1. [自定义模板](https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/cfg/Custom_Clash.ini)中的规则大量使用**ruleset**，默认情况下，ruleset的所有规则将会展开，不仅影响影响性能，而且还占内存。如果启用「使用规则集」，匹配速度更快（ 34 万规则 7 微秒），内存占用更小。
2. 另外，rule set 也分类型，classic 没有优化作用，ip cidr 和 domain 有强力的优化作用，这部分具体还是看 https://lancellc.gitbook.io/clash/clash-config-file/proxy-provider 
3. openclash的「配置管理」打开速度会更快，保存配置速度也更快。因为如果将ruleset展开之后，配置文件体积1M+，如果对于一些性能比较拉胯的设备，可能会导致openclash崩溃，就算是性能较强的设备，也能感觉到明显的卡顿。而启用「使用规则集」后，配置文件仅几十k，页面打开无压力。
4. 便于管理，在面板中能够清晰的看见各规则的详情以及更新时间。
![CleanShot 2024-09-24 at 13 35 09@2x](https://github.com/user-attachments/assets/197d966b-4b37-4b88-8d5d-a62497a575ae)

**注意：确保选择的订阅转换后端服务支持此功能，否则可能导致内核启动失败**

**Comment by Aethersailor** [comment]
感谢建议！
其实我在初次配置的时候也使用过规则集，后来之所以停用，是发现启用规则集后，每次更新配置文件并不会更新对应的规则，至少在面板中显示的更新时间不会变化。为了确保每天都会拉取一次最新的规则，所以干脆就停用了没有再多做研究。很好奇启用规则集的状态下，规则集的更新时间是受什么控制的？

**Comment by bdingtech** [comment]
在rule-providers里面有个interval可以设置规则集更新间隔。

更新时间不会变化是因为，**如果远端的文件和本地文件没有任何变化的话**，就不会进行覆盖，所以本地文件的修改日期也不会变化。出处：https://github.com/vernesong/OpenClash/issues/1957#issuecomment-1021204504

**Comment by Aethersailor** [comment]
> 在rule-providers里面有个interval可以设置规则集更新间隔。
> 
> 
> 
> 更新时间不会变化是因为，**如果远端的文件和本地文件没有任何变化的话**，就不会进行覆盖，所以本地文件的修改日期也不会变化。出处：https://github.com/vernesong/OpenClash/issues/1957#issuecomment-1021204504

感谢，后续我会修改wiki中的内容
