### ISSUE TITLE
acg.rip无法打开

### ISSUE THREAD

**Issue by seeson** [Aethersailor/Custom_OpenClash_Rules#42]
经查询，acg.rip已被墙，另部分torrent相关种子站均被墙，如kickasstorrents, badass torrents等，望大佬修改

**Comment by Aethersailor** [comment]
个性化需求请 fork 后自行修改，或者前往包含gfwlist的上游规则仓库进行反馈

**Comment by ghost** [comment]
> 个性化需求请 fork 后自行修改，或者前往包含gfwlist的上游规则仓库进行反馈

大佬，个性化方面有什么教程的吗。小白完全不知道搜什么关键词。谢谢🙏

**Comment by Aethersailor** [comment]
> > 个性化需求请 fork 后自行修改，或者前往包含gfwlist的上游规则仓库进行反馈
> 
> 大佬，个性化方面有什么教程的吗。小白完全不知道搜什么关键词。谢谢🙏

1. 编辑 Custom_Clash.ini 可以增删自己需要的策略组
2. 编辑 Custom_Direct.list 可以增删自己需要的冷门直连域名
3. 编辑 Custom_Proxy.list 可以增删自己需要的冷门代理域名

建议到 Youtube 上找一下相关的教学视频

**Comment by seeson** [comment]
> > > 个性化需求请 fork 后自行修改，或者前往包含gfwlist的上游规则仓库进行反馈
> > 
> > 
> > 大佬，个性化方面有什么教程的吗。小白完全不知道搜什么关键词。谢谢🙏
> 
> 1. 编辑 Custom_Clash.ini 可以增删自己需要的策略组
> 2. 编辑 Custom_Direct.list 可以增删自己需要的冷门直连域名
> 3. 编辑 Custom_Proxy.list 可以增删自己需要的冷门代理域名
> 
> 建议到 Youtube 上找一下相关的教学视频

求答疑，上游blackmatrix7使用domain-keyword导致关键字直连被墙网站，如何通过编辑git自行删除该条目？还是只能手动删除？
另外cutom_XXX.list 里的域名如果和rule-set有冲突是怎么处理的？会同样的规则写两条嘛？

**Comment by Aethersailor** [comment]
> > > > 个性化需求请 fork 后自行修改，或者前往包含gfwlist的上游规则仓库进行反馈
> > > 
> > > 
> > > 大佬，个性化方面有什么教程的吗。小白完全不知道搜什么关键词。谢谢🙏
> > 
> > 
> > 
> > 1. 编辑 Custom_Clash.ini 可以增删自己需要的策略组
> > 2. 编辑 Custom_Direct.list 可以增删自己需要的冷门直连域名
> > 3. 编辑 Custom_Proxy.list 可以增删自己需要的冷门代理域名
> > 
> > 建议到 Youtube 上找一下相关的教学视频
> 
> 求答疑，上游blackmatrix7使用domain-keyword导致关键字直连被墙网站，如何通过编辑git自行删除该条目？还是只能手动删除？ 另外cutom_XXX.list 里的域名如果和rule-set有冲突是怎么处理的？会同样的规则写两条嘛？



 Custom_Clash.ini 里面的 ruleset 是按照从上到下的优先级来遍历的，命中哪一条就按照哪一条生效，下放的规则碎片不会再遍历，因此即使同样的规则写两条也不会存在冲突的情况
所以优先级是 Custom_Direct.list > Custom_Proxy.list > 下方其他所有规则
因此，blackmatrix7 使用domain-keyword导致关键字直连被墙网站，你只要把这种误命中的域名添加进 Custom_Proxy.list 就可以解决被墙问题

**Comment by ghost** [comment]
> > > 个性化需求请 fork 后自行修改，或者前往包含gfwlist的上游规则仓库进行反馈
> > 
> > 
> > 大佬，个性化方面有什么教程的吗。小白完全不知道搜什么关键词。谢谢🙏
> 
> 1. 编辑 Custom_Clash.ini 可以增删自己需要的策略组
> 2. 编辑 Custom_Direct.list 可以增删自己需要的冷门直连域名
> 3. 编辑 Custom_Proxy.list 可以增删自己需要的冷门代理域名
> 
> 建议到 Youtube 上找一下相关的教学视频

好的谢谢，有空去看看。听你说就感觉复杂不知道能不能看懂教学视频。😂
