### ISSUE TITLE
百度搜索结果很多无法打开

### ISSUE THREAD

**Issue by andrewchenjp** [Aethersailor/Custom_OpenClash_Rules#43]
你好，我严格按照教程图片设置之后，发现百度的很多搜索结果链接无法打开，1688的旺旺网页对话框无法显示，甚至用idm下载1688的客户端无法下载，已经核对几次，设置都跟图片一致，不知是哪里出问题。

**Comment by Aethersailor** [comment]
检查打不开的链接的域名的解析结果

**Comment by andrewchenjp** [comment]
发现问题所在，把插件设置--流量控制--实验性：绕过中国大陆 IP 勾选去掉之后就正常了

**Comment by Aethersailor** [comment]
这个功能正常是可以启用的
更新一下 GEOIP 相关的数据库
