### ISSUE TITLE
使用这个规则模板会导致流媒体增强中迪士尼+解锁不生效

### ISSUE THREAD

**Issue by wuiiled** [Aethersailor/Custom_OpenClash_Rules#44]
规则模板切换ACL4SSR后，该功能正常
切换回本仓库规则模板后就无法运行迪士尼自动解锁

![微信截图_20240924004402](https://github.com/user-attachments/assets/5b5cc486-4710-4c3a-bb65-796ecbbe63ed)
![微信截图_20240924004430](https://github.com/user-attachments/assets/b1683eab-9eac-4237-a3c3-65003d837e18)

**Comment by CocoMilkMaster** [comment]
如果是能稳定解锁流媒体的机场，无需使用这个功能，在web控制面板代理策略组手动选择对应的解锁节点就行。

**Comment by Aethersailor** [comment]
试了下确实是这样，建议手动指定节点。

**Comment by wuiiled** [comment]
> 试了下确实是这样，建议手动指定节点。

机场节点解锁不稳定，非常需要这个功能

我也找了一下，还没发现是哪条规则的造成的

**Comment by Aethersailor** [comment]
> > 试了下确实是这样，建议手动指定节点。
> 
> 机场节点解锁不稳定，非常需要这个功能
> 
> 我也找了一下，还没发现是哪条规则的造成的

机场支持 ipv6 吗

**Comment by wuiiled** [comment]
> > > 试了下确实是这样，建议手动指定节点。
> > 
> > 
> > 机场节点解锁不稳定，非常需要这个功能
> > 我也找了一下，还没发现是哪条规则的造成的
> 
> 机场支持 ipv6 吗

支持ipv6入站，测试关了ipv6以后也是不生效

**Comment by Aethersailor** [comment]
> > > > 试了下确实是这样，建议手动指定节点。
> > > 
> > > 
> > > 机场节点解锁不稳定，非常需要这个功能
> > > 我也找了一下，还没发现是哪条规则的造成的
> > 
> > 
> > 机场支持 ipv6 吗
> 
> 支持ipv6入站，测试关了ipv6以后也是不生效

dnsmasq里禁用 AAAA 记录解析试试，不过我估计没效果

**Comment by wuiiled** [comment]
> > > > > 试了下确实是这样，建议手动指定节点。
> > > > 
> > > > 
> > > > 机场节点解锁不稳定，非常需要这个功能
> > > > 我也找了一下，还没发现是哪条规则的造成的
> > > 
> > > 
> > > 机场支持 ipv6 吗
> > 
> > 
> > 支持ipv6入站，测试关了ipv6以后也是不生效
> 
> dnsmasq里禁用 AAAA 记录解析试试，不过我估计没效果

不行，应该是规则中有点冲突

**Comment by Aethersailor** [comment]
local url = "https://disney.api.edge.bamgrid.com/devices"
	local url2 = "https://disney.api.edge.bamgrid.com/token"
	local url3 = "https://disney.api.edge.bamgrid.com/graph/v1/device/graphql"


我看了下 OpenClash 的解锁检测脚本中涉及 Disney+ 解锁的是这三个链接
bamgrid.com 域名已经正确的包含在了我的模板的 Disney+ 策略组中，因为我引用的是 blackmatrix7 的 Disney+ 规则，而这个规则的上游包含了 ACLRSSR 的 Disney+ 规则
并且在 Disney+ 的策略组之前的其他策略组是没有包含这个域名的分流的，也就是说分流是没有问题的

我怀疑可能是openclash解锁功能自身的问题，或者 luci 显示错误，因为我在 ssh 里直接运行解锁脚本是没有问题的，但是在 luci 中就会报错

**Comment by wuiiled** [comment]
在那边也提了个issue 脚本运行不报错，也看不出来到底哪里有问题

**Comment by Aethersailor** [comment]
我看到了，按照作者的意思似乎是脚本不报错就没有问题

**Comment by wuiiled** [comment]
对，手动运行脚本是可以检测并且自动换节点。luci界面显示错误的时候应该是出了什么问题导致脚本无法运行了

**Comment by Aethersailor** [comment]
> 对，手动运行脚本是可以检测并且自动换节点。luci界面显示错误的时候应该是出了什么问题导致脚本无法运行了

这好办，计划任务里设置一下定时运行一下脚本
luci估计只能等作者大佬修复了

**Comment by Aethersailor** [comment]
https://github.com/Aethersailor/Custom_OpenClash_Rules/commit/d0fa6e16a8fe3f17deec5845ec3a73e66e3fd216
