### ISSUE TITLE
openclash 教程wiki TYPO

### ISSUE THREAD

**Issue by jaychoww** [Aethersailor/Custom_OpenClash_Rules#47]
"弃用第二 DNS 服务器" 到底是启用还是弃用

**Comment by CocoMilkMaster** [comment]
是“启用第二 DNS 服务器”，阅读教程，这里不是让你勾选这个功能，而是解释这个功能的用途，是否勾选按自己需要。

**Comment by jaychoww** [comment]
谢谢, 原文表述有点迷惑, 会不会写成 **不要勾选‘启用第二DNS服务器’** 清晰一点

> 是“启用第二 DNS 服务器”，阅读教程，这里不是让你勾选这个功能，而是解释这个功能的用途，是否勾选按自己需要。

**Comment by Aethersailor** [comment]
> 谢谢, 原文表述有点迷惑, 会不会写成 **不要勾选‘启用第二DNS服务器’** 清晰一点
> 
> 
> 
> > 是“启用第二 DNS 服务器”，阅读教程，这里不是让你勾选这个功能，而是解释这个功能的用途，是否勾选按自己需要。
> 
> 
> 
> 

是否勾选要看个人需求，理解一些功能就明白了。
