### ISSUE TITLE
[旁路由] 出现DNS泄露

### ISSUE THREAD

**Issue by kxjgbh** [Aethersailor/Custom_OpenClash_Rules#49]
大佬好，首先感谢大佬的贡献，教程非常清晰明了。我还原了一遍默认配置，跟着教程一步一步配置，仍旧出现DNS泄露。

以下可能引起DNS泄露的原因都排除了一遍：
1. 漏网之鱼策略组没有选择“全球直连”
2. 配置订阅完全跟着教程走
3. 软路由已关闭IPV6
4. 没有使用第三方规则集
5. 电脑IPV4网关和DNS都设置成了软路由IP
6. NameServer只勾选了一个第三方DNS，Fallback和default-nameserver都未勾选

**不知道是不是以前修改过Dnsmasq的原因，我把动过的地方都贴出来**
![图片](https://github.com/user-attachments/assets/fb765b46-657d-4c6d-af3c-f7bc8288b32c)
![图片](https://github.com/user-attachments/assets/3fa134be-936f-4fa8-99d2-2e77f5ecf4fd)
![图片](https://github.com/user-attachments/assets/a772c5ee-1178-4d51-9eaa-485c25e1c5ef)
![图片](https://github.com/user-attachments/assets/79d7affa-d068-458e-b9b3-b61e555fc8ee)

### **想不到其余引起DNS泄露的原因了，想问问大佬有没有头绪，非常感谢！**

客户端版本：v0.46.034-beta，meta内核版本：alpha-g2647135

**Comment by Aethersailor** [comment]
浏览器不要使用安全dns

**Comment by kxjgbh** [comment]
> 浏览器不要使用安全dns

浏览器安全DNS一直是关的
![图片](https://github.com/user-attachments/assets/f84d3015-f7c7-4849-afc5-a8e79579faee)

**Comment by kxjgbh** [comment]
贴上我的dns字段：
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - 223.5.5.5
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.qq.com"
  - "+.tencent.com"
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.cdn.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - na.b.g-tun.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - shark007.net
  - Mijia Cloud
  - "+.cmbchina.com"
  - "+.cmbimg.com"
  - local.adguard.org
  - "+.sandai.net"
  - "+.n0808.com"
  - "+.uu.163.com"
  - ps.res.netease.com
  - "+.pub.3gppnetwork.org"
  - geosite:category-games
  - "+.services.googleapis.cn"
  - "+.googleapis.cn"
  - "+.xn--ngstr-lra8j.com"
  - geosite:cn
sniffer:
  enable: true
  parse-pure-ip: true
profile:
  store-selected: true
  store-fake-ip: true
experimental:
  sniff-tls-sni: false

**Comment by Aethersailor** [comment]
抱歉，我没有遇到过类似问题，看不出来问题所在，也许你可以尝试更新一下 GEOIP 数据库，或者更换固件
配置本身没有问题，如果出现问题肯定是配置之外的原因导致的

**Comment by kxjgbh** [comment]
> 抱歉，我没有遇到过类似问题，看不出来问题所在，也许你可以尝试更新一下 GEOIP 数据库，或者更换固件 配置本身没有问题，如果出现问题肯定是配置之外的原因导致的

不好意思浪费大佬精力了，您的配置完全没有问题。造成泄露是我自己的问题，刚刚更换测试设备才发现PC忘记关ipv6了，关闭v6后就不泄露了。感谢大佬回复！
