### ISSUE TITLE
添加第三方规则集后，出现DNS泄露

### ISSUE THREAD

**Issue by frank-we** [Aethersailor/Custom_OpenClash_Rules#5]
打算在规则附加功能里添加一个屏蔽广告的第三方规则集，结果发现出现了DNS泄露。
自定义添加的就没有出现问题。
因为和自定义模板里的规则出现冲突？
![image](https://github.com/Aethersailor/Custom_OpenClash_Rules/assets/66304894/f46728e2-8d30-492d-a803-79e6103b6e52)

**Comment by Aethersailor** [comment]
请上传第三方规则内容或者链接

我猜测是因为第三方规则中的 IP 规则没有添加 no-resolve，导致 openclash 将 IP 发给 nameserver 进行反向解析导致的泄漏

另外提醒一下，在本仓库的设置中大陆域名绕过内核的，所以用规则进行广告屏蔽无法过滤大陆的广告域名

**Comment by frank-we** [comment]
> 请上传第三方规则内容或者链接
> 
> 我猜测是因为第三方规则中的 IP 规则没有添加 no-resolve，导致 openclash 将 IP 发给 nameserver 进行反向解析导致的泄漏
> 
> 另外提醒一下，在本仓库的设置中大陆域名绕过内核的，所以用规则进行广告屏蔽无法过滤大陆的广告域名

你是对的，该规则集中的IP没添加no-resolve。
相关地址：https://github.com/dler-io/Rules/blob/main/Clash/Provider/Reject.yaml
谢谢你的教程😀

**Comment by ghost** [comment]
我没添加也泄露了，我也不知道问题所在，还是跟着教程一步步设置的。愁人。

**Comment by Aethersailor** [comment]
> 我没添加也泄露了，我也不知道问题所在，还是跟着教程一步步设置的。愁人。

如果是100%按照教程操作的，并且使用了本仓库的订阅模板，不可能存在泄露哦
检查一下浏览器的安全 DNS 设置，必须关闭

**Comment by ghost** [comment]
> > 我没添加也泄露了，我也不知道问题所在，还是跟着教程一步步设置的。愁人。
> 
> 如果是100%按照教程操作的，并且使用了本仓库的订阅模板，不可能存在泄露哦 检查一下浏览器的安全 DNS 设置，必须关闭

这个一直都是关着的，最开始设置的时候不泄露，然后某天去查看的时候就泄露了，前两天不泄露了，现在又开始了。我就很惆怅=。=

**Comment by Aethersailor** [comment]
> > > 我没添加也泄露了，我也不知道问题所在，还是跟着教程一步步设置的。愁人。
> > 
> > 
> > 如果是100%按照教程操作的，并且使用了本仓库的订阅模板，不可能存在泄露哦 检查一下浏览器的安全 DNS 设置，必须关闭
> 
> 这个一直都是关着的，最开始设置的时候不泄露，然后某天去查看的时候就泄露了，前两天不泄露了，现在又开始了。我就很惆怅=。=

设置未改变的情况下，时而泄露时而不泄露？那这和本仓库的模板无关了，因为模板中对于防泄漏的分流是写死的了，不会出现时而泄露时而不泄露的情况
你是不是关闭了 openclash 的 ipv6 但是打开了 openwrt 的 ipv6 ？

**Comment by ghost** [comment]
> > > > 我没添加也泄露了，我也不知道问题所在，还是跟着教程一步步设置的。愁人。
> > > 
> > > 
> > > 如果是100%按照教程操作的，并且使用了本仓库的订阅模板，不可能存在泄露哦 检查一下浏览器的安全 DNS 设置，必须关闭
> > 
> > 
> > 这个一直都是关着的，最开始设置的时候不泄露，然后某天去查看的时候就泄露了，前两天不泄露了，现在又开始了。我就很惆怅=。=
> 
> 设置未改变的情况下，时而泄露时而不泄露？那这和本仓库的模板无关了，因为模板中对于防泄漏的分流是写死的了，不会出现时而泄露时而不泄露的情况 你是不是关闭了 openclash 的 ipv6 但是打开了 openwrt 的 ipv6 ？

没有，ipv6我觉得太复杂，都是关闭的状态。不过我是旁路由，我也看你的帖子有旁路由相关设置，我也跟着做的-。-全抄~ 要不我有空再去核对一下你的帖子吧。谢谢大佬！~

**Comment by Aethersailor** [comment]
> > > > > 我没添加也泄露了，我也不知道问题所在，还是跟着教程一步步设置的。愁人。
> > > > 
> > > > 
> > > > 如果是100%按照教程操作的，并且使用了本仓库的订阅模板，不可能存在泄露哦 检查一下浏览器的安全 DNS 设置，必须关闭
> > > 
> > > 
> > > 这个一直都是关着的，最开始设置的时候不泄露，然后某天去查看的时候就泄露了，前两天不泄露了，现在又开始了。我就很惆怅=。=
> > 
> > 
> > 设置未改变的情况下，时而泄露时而不泄露？那这和本仓库的模板无关了，因为模板中对于防泄漏的分流是写死的了，不会出现时而泄露时而不泄露的情况 你是不是关闭了 openclash 的 ipv6 但是打开了 openwrt 的 ipv6 ？
> 
> 没有，ipv6我觉得太复杂，都是关闭的状态。不过我是旁路由，我也看你的帖子有旁路由相关设置，我也跟着做的-。-全抄~ 要不我有空再去核对一下你的帖子吧。谢谢大佬！~

好，再检查一下吧，或者自己摸索一下，我太久不用旁路由了，旁路由的一套设置也只是在朋友家的 openwrt 上设置过一次，细节也可能不完善
我这套设置的逻辑其实很简单，dnsmasq 按照大陆域名分流，国内域名交运营商 DNS ，国外域名交 openclash ，ipleak.net 域名的解析最后必然是命中 ruleset=🐟 漏网之鱼,[]FINAL 这条规则最后走远端节点解析的
你可以在浏览器上安装一个 IPvFoo 插件，观察一下 ipleak.net 网页返回的 ip 地址是否有非 fake-ip 范围的地址

**Comment by ghost** [comment]
> > > > > > 我没添加也泄露了，我也不知道问题所在，还是跟着教程一步步设置的。愁人。
> > > > > 
> > > > > 
> > > > > 如果是100%按照教程操作的，并且使用了本仓库的订阅模板，不可能存在泄露哦 检查一下浏览器的安全 DNS 设置，必须关闭
> > > > 
> > > > 
> > > > 这个一直都是关着的，最开始设置的时候不泄露，然后某天去查看的时候就泄露了，前两天不泄露了，现在又开始了。我就很惆怅=。=
> > > 
> > > 
> > > 设置未改变的情况下，时而泄露时而不泄露？那这和本仓库的模板无关了，因为模板中对于防泄漏的分流是写死的了，不会出现时而泄露时而不泄露的情况 你是不是关闭了 openclash 的 ipv6 但是打开了 openwrt 的 ipv6 ？
> > 
> > 
> > 没有，ipv6我觉得太复杂，都是关闭的状态。不过我是旁路由，我也看你的帖子有旁路由相关设置，我也跟着做的-。-全抄~ 要不我有空再去核对一下你的帖子吧。谢谢大佬！~
> 
> 好，再检查一下吧，或者自己摸索一下，我太久不用旁路由了，旁路由的一套设置也只是在朋友家的 openwrt 上设置过一次，细节也可能不完善 我这套设置的逻辑其实很简单，dnsmasq 按照大陆域名分流，国内域名交运营商 DNS ，国外域名交 openclash ，ipleak.net 域名的解析最后必然是命中 ruleset=🐟 漏网之鱼,[]FINAL 这条规则最后走远端节点解析的 你可以在浏览器上安装一个 IPvFoo 插件，观察一下 ipleak.net 网页返回的 ip 地址是否有非 fake-ip 范围的地址

啊？漏网之鱼？这条我选择了「全球直连」，是否是因为这个的缘故？😲
。。。。。漏网之鱼选择「节点」后，不泄露了。
![VW8ROBRV777PS_DWGZP$92](https://github.com/Aethersailor/Custom_OpenClash_Rules/assets/98329765/a9fc3203-7d2c-4d3c-a84d-95177cebd843)

**Comment by Aethersailor** [comment]
> > > > > > > 我没添加也泄露了，我也不知道问题所在，还是跟着教程一步步设置的。愁人。
> > > > > > 
> > > > > > 
> > > > > > 如果是100%按照教程操作的，并且使用了本仓库的订阅模板，不可能存在泄露哦 检查一下浏览器的安全 DNS 设置，必须关闭
> > > > > 
> > > > > 
> > > > > 这个一直都是关着的，最开始设置的时候不泄露，然后某天去查看的时候就泄露了，前两天不泄露了，现在又开始了。我就很惆怅=。=
> > > > 
> > > > 
> > > > 设置未改变的情况下，时而泄露时而不泄露？那这和本仓库的模板无关了，因为模板中对于防泄漏的分流是写死的了，不会出现时而泄露时而不泄露的情况 你是不是关闭了 openclash 的 ipv6 但是打开了 openwrt 的 ipv6 ？
> > > 
> > > 
> > > 没有，ipv6我觉得太复杂，都是关闭的状态。不过我是旁路由，我也看你的帖子有旁路由相关设置，我也跟着做的-。-全抄~ 要不我有空再去核对一下你的帖子吧。谢谢大佬！~
> > 
> > 
> > 好，再检查一下吧，或者自己摸索一下，我太久不用旁路由了，旁路由的一套设置也只是在朋友家的 openwrt 上设置过一次，细节也可能不完善 我这套设置的逻辑其实很简单，dnsmasq 按照大陆域名分流，国内域名交运营商 DNS ，国外域名交 openclash ，ipleak.net 域名的解析最后必然是命中 ruleset=🐟 漏网之鱼,[]FINAL 这条规则最后走远端节点解析的 你可以在浏览器上安装一个 IPvFoo 插件，观察一下 ipleak.net 网页返回的 ip 地址是否有非 fake-ip 范围的地址
> 
> 啊？漏网之鱼？这条我选择了「全球直连」，是否是因为这个的缘故？😲 。。。。。漏网之鱼选择「节点」后，不泄露了。 ![VW8ROBRV777PS_DWGZP$92](https://private-user-images.githubusercontent.com/98329765/344451588-a9fc3203-7d2c-4d3c-a84d-95177cebd843.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzkwODIsIm5iZiI6MTcxOTczODc4MiwicGF0aCI6Ii85ODMyOTc2NS8zNDQ0NTE1ODgtYTlmYzMyMDMtN2QyYy00ZDNjLWE4NGQtOTUxNzdjZWJkODQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDA5MTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNDhhN2U1N2Q5Yzk0MjczYzc0NmQ3ZWI3ZjRjYjU5NzEzZTFhNzgyMDQ5NGFlYjk5YjIyOGU5NTJiZTlkM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eMJ3ILpi4X2IBW75K2w45arky4RRHpJW_1vqMyzIM0U)

是的，就是这个缘故
没有命中任何一条上游规则的域名或 IP 最后都会命中漏网之鱼，如果漏网之鱼选直连了 ipleak.net 的域名会交给 nameserver 解析，当然就泄露了

**Comment by ghost** [comment]
好的，那这条就默认了不直连了。谢谢大佬！😄😄😄
