### ISSUE TITLE
hysteria2协议的机场转换后会出现问题

### ISSUE THREAD

**Issue by huojinming-1997** [Aethersailor/Custom_OpenClash_Rules#50]
因为默认的后端无法转换hysteria2所以自己在本地搭建了asdlokj1qpi23/subconverter这个容器作为后端转换，能转换成功但在面板上hysteria2节点显示灰色不能使用，希望能有一个配合这个规则的后端转换配合使用就好啦因为现在用hysteria2协议的机场越来越多

**Comment by Aethersailor** [comment]
多找找试试，应该有订阅服务支持的
