### ISSUE TITLE
建议配置教程中开启覆写设置中规则设置的仅代理命中规则流量

### ISSUE THREAD

**Issue by sun1a2b3c** [Aethersailor/Custom_OpenClash_Rules#57]
这样可以规避 BT、P2P 下载流量经过代理，这样就不需要再手动去漏网之鱼中选择直连了（况且教程本身也不推荐这么做）。

**Comment by paysenyu** [comment]
弱弱的请教一下，开了这个之后是不是和漏网之鱼冲突了。

我个人理解。仅代理命中规则  = 漏网之鱼直连

**Comment by sun1a2b3c** [comment]
> 弱弱的请教一下，开了这个之后是不是和漏网之鱼冲突了。
> 
> 我个人理解。仅代理命中规则 = 漏网之鱼直连

不会，我有看过，漏网之鱼依然走的代理。

**Comment by paysenyu** [comment]
> > 弱弱的请教一下，开了这个之后是不是和漏网之鱼冲突了。
> > 我个人理解。仅代理命中规则 = 漏网之鱼直连
> 
> 不会，我有看过，漏网之鱼依然走的代理。

那这简直太棒了。。但是好好奇怎么实现的。。。。😂

**Comment by sun1a2b3c** [comment]
> > > 弱弱的请教一下，开了这个之后是不是和漏网之鱼冲突了。
> > > 我个人理解。仅代理命中规则 = 漏网之鱼直连
> > 
> > 
> > 不会，我有看过，漏网之鱼依然走的代理。
> 
> 那这简直太棒了。。但是好好奇怎么实现的。。。。😂

这你得去问开发者，我只是个普通用户……😓

**Comment by Aethersailor** [comment]
https://github.com/vernesong/OpenClash/issues/3942

有一定副作用，自行取舍即可
经常下载就开启，不经常下载可以关闭
已经更新 wiki 内对应内容，感谢建议
https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%A1%88#%E8%A7%84%E5%88%99%E8%AE%BE%E7%BD%AE
