### ISSUE TITLE
最新版本0.46.043修改了dnsmasq和firewall的启动顺序，去广告教程失效

### ISSUE THREAD

**Issue by JIZHENQIANG** [Aethersailor/Custom_OpenClash_Rules#59]
![捕获](https://github.com/user-attachments/assets/4ab6ac1e-1d2f-4396-aa0f-614d999a2c4d)

**Comment by Aethersailor** [comment]
加一行指令清理 dnsmasq 缓存即可，已更新设置方法

**Comment by JIZHENQIANG** [comment]
> 加一行指令清理 dnsmasq 缓存即可，已更新设置方法

没有起作用。/tmp/dnsmasq.d文件夹里面没有下载的文件呢？
![捕获](https://github.com/user-attachments/assets/cf597373-52ed-4fad-812a-ba1c5fb0ecc1)

**Comment by Aethersailor** [comment]
我这边是用的是正常的，ssh下直接用命令下载一下试试，排除一下网络问题

**Comment by JIZHENQIANG** [comment]
不是网络问题，感觉是被删除了或者没有输出到这个目录。
刚才找了一下没看到哪里有删除这个的，但是把dnsmasq和firewall两个顺序换回来就行。无语了
明天重装一下ImmortalWrt系统再看看是不是clash更新版本有残留的问题，今天先改了配置文件把启动顺序换回来将就用吧。

**Comment by zhy95** [comment]
![屏幕截图 2024-10-13 162114](https://github.com/user-attachments/assets/453a6499-148e-46d6-970a-5c293ba3bca5)
也是0.46.043，一直提示  守护程序：检测到防火墙规则顺序有误，修改插件防火墙规则...

**Comment by Aethersailor** [comment]
> ![屏幕截图 2024-10-13 162114](https://github.com/user-attachments/assets/453a6499-148e-46d6-970a-5c293ba3bca5)
> 
> 也是0.46.043，一直提示  守护程序：检测到防火墙规则顺序有误，修改插件防火墙规则...

模板不会影响这个，一般是系统里有其他插件在修改防火墙规则，最好带着 log 去 OpenClash 仓库提 issue

**Comment by JIZHENQIANG** [comment]
> 我这边是用的是正常的，ssh下直接用命令下载一下试试，排除一下网络问题

今天重装了系统也不行，不知道是哪里问题，我感觉是设置firewall的时候删除了规则或者重置了网络之类的。但是你说你那边没问题，那可能是ImmortalWrt系统的问题。你用的是不是ImmortalWrt？

**Comment by Aethersailor** [comment]
> > 我这边是用的是正常的，ssh下直接用命令下载一下试试，排除一下网络问题
> 
> 今天重装了系统也不行，不知道是哪里问题，我感觉是设置firewall的时候删除了规则或者重置了网络之类的。但是你说你那边没问题，那可能是ImmortalWrt系统的问题。你用的是不是ImmortalWrt？

我5台设备都是 ImmortalWrt  没有任何问题
`curl -s https://anti-ad.net/anti-ad-for-dnsmasq.conf -o /tmp/dnsmasq.d/anti-ad-for-dnsmasq.conf`
先关闭 openclash，在ssh里尝试用以上命令下载去广告规则能否成功

**Comment by JIZHENQIANG** [comment]
好的，可能我这路由器有什么毛病吧。不过改一下firewall和dnsmasq顺序能解决，我自己手动改一下吧，就是不知道openclash的作者为什么要修改这个顺序，以前都好好的。

**Comment by Aethersailor** [comment]
> 好的，可能我这路由器有什么毛病吧。不过改一下firewall和dnsmasq顺序能解决，我自己手动改一下吧，就是不知道openclash的作者为什么要修改这个顺序，以前都好好的。

换个思路，用系统计划任务可以实现相同的操作，不依赖openclash

**Comment by JIZHENQIANG** [comment]
最开始就是想加入启动项脚本的，后来在你这看了去广告和openclash一起启动也不错还免得了有启动顺序些问题

**Comment by yichen11818** [comment]
> 好的，可能我这路由器有什么毛病吧。不过改一下firewall和dnsmasq顺序能解决，我自己手动改一下吧，就是不知道openclash的作者为什么要修改这个顺序，以前都好好的。

你好能否告知一下如何修改顺序

**Comment by yichen11818** [comment]
> ![屏幕截图 2024-10-13 162114](https://private-user-images.githubusercontent.com/70793615/376019195-453a6499-148e-46d6-970a-5c293ba3bca5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NjQ4MzYsIm5iZiI6MTczMDc2NDUzNiwicGF0aCI6Ii83MDc5MzYxNS8zNzYwMTkxOTUtNDUzYTY0OTktMTQ4ZS00NmQ2LTk3MGEtNWMyOTNiYTNiY2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDIzNTUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNGRmNmM2NTk2YzJmMmRkOTUxOTVjOTUyNDQyMjViNGM5OTk5MDNlMGY5NjNmMTRiM2QwZTg4NTk1YTljODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HQX_7m12Hsj3lD_zXFO9sLsOOsZ-BEDORwxuP2fx-Io) 也是0.46.043，一直提示 守护程序：检测到防火墙规则顺序有误，修改插件防火墙规则...

同样的问题 困扰很久了

**Comment by kokoipz** [comment]
用ssh就行了。`curl -s https://ghfast.top/https://raw.githubusercontent.com/kokoipz/AX6-OpenWRT/refs/heads/main/ad.sh | sh`
然后设置计划任务
