### ISSUE TITLE
您好，关于该配置我有些问题想咨询一下

### ISSUE THREAD

**Issue by aaseud** [Aethersailor/Custom_OpenClash_Rules#64]
第一次接触openwrt，请问该规则没覆盖的需要走代理的网站（或者不需要走代理的）可以自己在配置管理里添加吗，每日更新后会失效吗，失效的话怎么办呢

**Comment by JIZHENQIANG** [comment]
自定义规则应该可以达到你想要的效果
![捕获](https://github.com/user-attachments/assets/b4ecda84-de18-4040-8d3d-ea8d8e2de2aa)

**Comment by aaseud** [comment]
原来在这！谢谢！
