### ISSUE TITLE
按照教程设置之后，我打开知乎等国内网站，结果显示我在日本

### ISSUE THREAD

**Issue by wujun4code** [Aethersailor/Custom_OpenClash_Rules#65]
我是完全按照教程一步一步设置的，并且启用了
![image](https://github.com/user-attachments/assets/6b26c9cf-97aa-40f5-b56e-4340adef3dff)

我发现我windows 上登陆的微信以及浏览器打开知乎等网站，全都i是走的代理，我也用了你的订阅模板，我搞了一个星期都没搞定，不知道是哪里有问题。

**Comment by Aethersailor** [comment]
1. 更新 openclash 和 内核为最新版
2. 更新 GEO 数据库和大陆白名单
3. 观察 dashboard 中分流情况，正常情况下不应显示知乎的连接

**Comment by wujun4code** [comment]
@Aethersailor 我全都照做了

![image](https://github.com/user-attachments/assets/45ca37b9-2f30-4dad-a000-439d19dc88ff)


![image](https://github.com/user-attachments/assets/00a45999-5979-4606-af84-8c05b2fd9612)

现在显示的还是对的，等运行一段时间，它就会莫名奇妙的把
![image](https://github.com/user-attachments/assets/bcb48c0c-45a2-40d6-88d6-15bfe9298485)

**Comment by wujun4code** [comment]
![image](https://github.com/user-attachments/assets/6319e216-3c2f-4533-bf5c-9a8c9037270a)

果然如上图所示，不到2个小时就会变回这个样子。

**Comment by Aethersailor** [comment]
如果是开启绕过大陆以后过一段时间会失效，那这个问题最好去openclash的仓库下提问，带着log，看看开发者怎么说

**Comment by wujun4code** [comment]
我也试过关掉这个【开启绕过大陆】的功能，也会出现这个问题。

**Comment by Aethersailor** [comment]
看日志里有什么信息

**Comment by wujun4code** [comment]
![image](https://github.com/user-attachments/assets/52cad390-0359-4253-aabc-058649370346)

这里面有一个是知乎的 ip，第一次打开知乎，他会走一次域名匹配，能匹配到 直连，然后后续应该都是直接的  keep-alive 的 tcp 请求了，后面就逐渐的被匹配到了漏网之鱼了，应该是这个问题，所以还是说知乎的 ip 可能也不是固定的，每天也在变化，所以 openclash 的大陆 ip 库，未必能精准。

**Comment by Aethersailor** [comment]
https://github.com/vernesong/OpenClash/issues/3999
我看到有人遇到过类似问题

这应该是插件自身的问题了，我没法解决，去openclash仓库下提问吧

**Comment by Aethersailor** [comment]
pc下用nslookup检查一下知乎的解析结果

**Comment by samishia** [comment]
建议漏网之鱼还是选择direct吧，这样小众的国内网站不会走代理了，还能规避bt和pt下载走代理带来的机场流量浪费，如果希望某些小众网站走代理，还能通过附加规则让它强行走代理
