### ISSUE TITLE
B站直播提示DNS错误是，直播时上层状态栏失效

### ISSUE THREAD

**Issue by Asuka-EVA-02** [Aethersailor/Custom_OpenClash_Rules#66]

**Comment by Aethersailor** [comment]
本仓库提供的仅仅是设置方案和订阅转换模板，不会导致 openclash 工作异常
正确设置后，B站相关域名会绕过内核直连，且模板中已经设置了“国内媒体”策略组，对应规则兜底了B站域名
DNS 解析不正常，请自行按照以下步骤查找原因
nslookup 查看相关域名解析情况，如果是 Fake-IP 则说明绕过大陆功能没有正确生效，具体解决方法需要去 openclash 仓库提问

**Comment by Asuka-EVA-02** [comment]
> 本仓库提供的仅仅是设置方案和订阅转换模板，不会导致 openclash 工作异常
> 正确设置后，B站相关域名会绕过内核直连，且模板中已经设置了“国内媒体”策略组，对应规则兜底了B站域名
> DNS 解析不正常，请自行按照以下步骤查找原因
> nslookup 查看相关域名解析情况，如果是 Fake-IP 则说明绕过大陆功能没有正确生效，具体解决方法需要去 openclash 仓库提问
> 

感谢回复

找到问题了，应该是添加了第三方规则的问题

建议把转换模板的手动选择和节点选择做到一起，或者出一个解释教程，使用会上比较疑惑，不知道以哪个为准

**Comment by Aethersailor** [comment]
> > 本仓库提供的仅仅是设置方案和订阅转换模板，不会导致 openclash 工作异常
> > 正确设置后，B站相关域名会绕过内核直连，且模板中已经设置了“国内媒体”策略组，对应规则兜底了B站域名
> > DNS 解析不正常，请自行按照以下步骤查找原因
> > nslookup 查看相关域名解析情况，如果是 Fake-IP 则说明绕过大陆功能没有正确生效，具体解决方法需要去 openclash 仓库提问
> 
> 感谢回复
> 
> 找到问题了，应该是添加了第三方规则的问题
> 
> 建议把转换模板的手动选择和节点选择做到一起，或者出一个解释教程，使用会上比较疑惑，不知道以哪个为准

这个是参考 ACL4SSR 模板来的，稍微看一下就能理解
