### ISSUE TITLE
Mac 端的 app store 无法访问，请问如何解决

### ISSUE THREAD

**Issue by cq0121** [Aethersailor/Custom_OpenClash_Rules#67]

**Comment by Aethersailor** [comment]
本仓库提供的仅仅是设置方案和订阅转换模板，不会导致 openclash 工作异常（openclash 自身问题除外）
正确设置后，包括 App Store 在内的 Apple 相关域名会直连
如果你访问的域名未能命中 Apple 规则，请通过 dashboard 自行排查相关域名，然后去上游规则对应仓库进行反馈
