### ISSUE TITLE
vpn连接上后无法科学上网

### ISSUE THREAD

**Issue by lexin8** [Aethersailor/Custom_OpenClash_Rules#71]
固件
ImmortalWrt 23.05-SNAPSHOT r28081-f213890acd / LuCI openwrt-23.05 branch git-24.291.29217-8d80e6b

openclash：v0.46.046-beta版本 ；type: hysteria2协议

使用L2TP协议连接上主路由；手机、PC端都正常；openwrt使用L2TP协议拨号后内外网正常，就是不能翻墙。

PS：换过很多固件跟版本，个人感觉是DNS解析问题，不会设置

`https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%A1%88`

也按照该配置进行设置也存在同样问题。homeproxy，passwall不存在该问题。

**Comment by Aethersailor** [comment]
无力解决，非本项目内容引起的故障，建议移步 openclash 仓库下提问
