### ISSUE TITLE
建议在Copilot策略组中增加全球直连

### ISSUE THREAD

**Issue by TDSY666** [Aethersailor/Custom_OpenClash_Rules#73]
最近配置更新后，原来Copilot策略组的全球直连没了，导致bing只能走代理，有时抽风会搜不出东西。

**Comment by Aethersailor** [comment]
done.
1b5efb995bb4bcd8025c6f28ba8fa4d90a327bb2

**Comment by jackieyiwu** [comment]
> 最近配置更新后，原来Copilot策略组的全球直连没了，导致bing只能走代理，有时抽风会搜不出东西。

不要用edge   用谷歌或海外版的firefox
