### ISSUE TITLE
反馈一些问题

### ISSUE THREAD

**Issue by ghost** [Aethersailor/Custom_OpenClash_Rules#74]
在我fork了大佬的项目，和油土鳖上的教学视频，我改变了某些项目后感觉规则流畅了一些：（以下你的称为原版）

1.「ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve」 建议去掉「no-resolve」，原版的话，比如美物清单，暗房，焦作水务，bing等网站会 match 漏网之鱼走代理。去掉后这四个网站会 match GeoIP(cn) 使用直连[DIRECT]。

2.「;ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list 」
建议保留「ChinaMax.list」去掉剩下的三个，我发现「ChinaMax.list」里面包含有剩下的这三个中大部分的，感觉会重复，而且去掉这三个后我发现之前走代理的「client.wns.windows.com」「edge.microsoft.com」「time.apple.com」「*.itunes.apple.com」等域名，现在都正常 match 各自的规则集了，包括 GitHub 也是，现在就正常 match github 规则集了，感觉强迫症的福音。原版的话这几个域名全是漏网之鱼。

（说来也奇怪，本身就有 github 规则集，但是日志里反馈的全是走的漏网之鱼，去掉这三个 ruleset 直连倒是正常的，但是直连跟 github 有什么关系？难道里面有以上的域名或者 IP ？有点超纲。）

以上。我是小白有些问题讲不出所以然，只能说下对比差异，就是发出来给大佬做个参考。

谢谢。😄

**Comment by Aethersailor** [comment]
1. 去掉 no-resolve 会导致 DNS 泄露。
为了避免 DNS 泄露问题（哪怕仅仅不能通过泄露检测的假泄露也包括在内），所以不会去掉如上的参数。  
冷门国内域名（比如焦作水务）需要自己根据需求补全规则或者使用 OpenClash的自定义规则功能，或者向 geosite 仓库提交 PR。如果仅仅是少量冷门无名，建议使用自定义规则功能。  
bing 有对应的规则（Copilot）不会命中漏网之鱼。如果是 bing 中国站，会绕过内核。  
如有异常，请检查转换后的配置文件是否完整，是否有内容缺失。

2. 不存在规则重复的情况。 
在本项目的模板中， ChinaMax.list 其实一直是**被注释掉**的，这一行从未生效过（你复制的内容中也可以看到该规则前的注释符号）。
注释掉它是因为它的体积太大，大部分订阅转换网站并不支持，会导致转换后的配置文件内容残缺。所以这一行始终是弃用的状态，是否删除它对模板本身并没有任何影响。  
如果你启用了它，那大概率你转换后的配置文件内容是不完整的。  
ChinaMax.list 中包含的也大多是国内主流网站，很多冷门域名也没有。况且在 OpenClash 已经根据 GEOSITE / GEOIP 进行了绕过内核操作，引用这个巨大的规则文件属实没有必要。所以采用 ACL4SSR 的三个规则进行兜底，性能更佳。  

3. 其他说明  
从原理上来说，规则集是按照从上到下的顺序遍历的，原版中 Microsoft、Apple、Github 相关的连接会优先命中各自对应的规则，不可能被下面的 China 相关规则影响，何况 China 规则中也没有与之相关的域名，更不可能影响其不包含的域名是否 match 对应的规则。  
原版中这些域名也不会走漏网之鱼。如果走了漏网之鱼，说明转换后的配置文件中缺少了对应的规则。  
![1](https://github.com/user-attachments/assets/88efc82d-d6d6-4a8b-bcab-cd00fe832640)
![2](https://github.com/user-attachments/assets/ddbf916f-324a-4d5b-9a81-541ab948a646)

以上问题并非模板导致的。  
如果你的 Github、Microsoft、Apple 相关域名走了漏网之鱼，或者其他域名未能按照预期进行分流。说明你的配置文件中关于分流的内容不全，缺失对应的规则，或者配置不正确。请先检查转换后的配置文件是否完整。  

更多内容请参考 [Wiki 故障排除](https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4#5-%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)章节。

**Comment by ghost** [comment]
get .
继续测试。
谢谢😄
