### ISSUE TITLE
如何使广告拦截配合OpenClash使用

### ISSUE THREAD

**Issue by EricZhou05** [Aethersailor/Custom_OpenClash_Rules#78]
有黑白名单需求，希望一些客户端绕过clash

![image](https://github.com/user-attachments/assets/8a5e895e-7e98-4ab2-98eb-b75ec2ec5e29)

但是名单要生效本地 DNS 劫持就不能使用 Dnsmasq 转发，必须要使用防火墙转发。

![image](https://github.com/user-attachments/assets/6a2462d3-29ab-4179-97c8-5fc9c46b83f1)

这就导致了广告拦截的失效。

有没有办法实现既有广告拦截然后又可以让一些客户端绕过clash不走代理呢。

其实走也没问题，只要有办法让clash处理局域网某些指定ip的请求时都导向全球直连就行

**Comment by EricZhou05** [comment]
我想到一个好方法：
直接覆写设置-规则附加自定义规则让源ip直连

`- SRC-IP-CIDR,192.168.2.185/32,DIRECT`
或者
`- "SRC-IP-CIDR,192.168.2.185/32,\U0001F3AF 全球直连,no-resolve"`

就是DHCP难解决，可能要给设备绑静态IP

**Comment by Aethersailor** [comment]
> 我想到一个好方法：
> 
> 直接覆写设置-规则附加自定义规则让源ip直连
> 
> 
> 
> `- SRC-IP-CIDR,192.168.2.185/32,DIRECT`
> 
> 或者
> 
> `- "SRC-IP-CIDR,192.168.2.185/32,\U0001F3AF 全球直连,no-resolve"`
> 
> 
> 
> 就是DHCP难解决，可能要给设备绑静态IP

这是个好办法
可以先尝试不绑定静态IP，因为Openwrt的dhcp分配的动态地址也是相对固定的，地址池不占满的情况下，几乎不会变动

**Comment by Aethersailor** [comment]
思路很好，干嘛删了

**Comment by maimaiguanfan** [comment]
> 思路很好，干嘛删了

这种方法设置的“黑名单”设备的IPv6仍会走代理，我先研究一下，如果是纯IPv4的网络确实可以用这种办法。

**Comment by maimaiguanfan** [comment]
> 思路很好，干嘛删了

原文贴回来，补充说明一下：IPv6 仍会走代理，仅纯 IPv4 网络可以做到完美分流。

现在我把 lan 口（192.168.40.1/24）的 dhcp 设置为启动：128，客户数：120（对应分配 192.168.40.128 - 192.168.40.248 的地址）。

然后 Openclash 覆写设置自定义规则添加：

`- SRC-IP-CIDR,192.168.40.128/25,DIRECT`

最终效果：
1. Openclash 的“本地 DNS 劫持”可以设置为“使用 Dnsmasq 转发”；
2. 局域网内所有设备可以通过 luci-app-adblock 插件正常拦截广告；
3. 陌生设备首次接入网络时，分配到 192.168.40.128 - 192.168.40.248 的地址，因此即便流量经过 Openclash 核心，也只会被分类到走DIRECT规则，做到默认情况下接入网络即为黑名单状态；
4. 需要走代理的设备手动分配 192.168.40.2 - 192.168.40.127 之间的静态地址，即可实现正常按规则进行代理。

**Comment by EricZhou05** [comment]
学习了🙏
