### ISSUE TITLE
谷歌商店规则冲突

### ISSUE THREAD

**Issue by darknesswei** [Aethersailor/Custom_OpenClash_Rules#79]
大佬，你用的bm7的Direct.list里写了直连的谷歌，后面Custom_Proxy又是强制走代理。
我也是一直手机谷歌商店连不动，今天重搓配置发现的。
有网友说xn--ngstr-lra8j.com要走直连，services.googleapis.cn走代理，我一会试试。

**Comment by Aethersailor** [comment]
Custom_Proxy 的优先级在 bm7 规则之上，目前安排的是这两条域名强制走代理
这是根据以前的 issue 反馈情况设置的，可能和现在的情况不一样，我没法测试因为我没有安卓设备。。
你可以测试一下，应该是走代理还是直连，我来进行相应的修改

**Comment by darknesswei** [comment]
使用DNS:1.1.1.1 测试以下规则：
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,全球直连         #直连下载速度极快，改为节点同样能下载，速度慢，可能跟vps有关
  - DOMAIN-SUFFIX,clientservices.googleapis.com,节点
  - DOMAIN-SUFFIX,services.googleapis.cn,节点 

测试结论： 
1.绕过大陆模式下使用fakeip黑名单模式，不添加- 'geosite:geolocation-!cn'一直转圈，加上之后瞬间通畅。
2.不绕过大陆模式，给谷歌返回vps的ip也没用，无论是直连还是节点都无法下载。  
补充：使用的是https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat，
bm7的Direct.list里clientservices.googleapis.com规则给的是直连，我改成节点了，能用也没往下测。

**Comment by Aethersailor** [comment]
done.
https://github.com/Aethersailor/Custom_OpenClash_Rules/commit/0404fc7dd3a83abec87fd43652c6e16cdb9aef21
