### ISSUE TITLE
反馈一个问题：订阅转换可能有问题

### ISSUE THREAD

**Issue by li5bo5** [Aethersailor/Custom_OpenClash_Rules#8]
我机场用了订阅转换，youtube、github、google都打不开。。。。
添加同一个订阅，不进行转换，就可以正常打开
两个配置只有下图有区别，其他的任何地方都一样
![无标题](https://github.com/user-attachments/assets/3ec325af-0290-4762-860b-8e5b262fb395)

**Comment by li5bo5** [comment]
国内网站都可以正常打开

**Comment by Aethersailor** [comment]
我猜测你填入的应该是机场提供的 Clash 订阅链接，这种链接不需要转换，所以你在 OpenClash 里二次转换当然不能使用了
应当使用普通的节点订阅链接或者 v2RayN/Shadowrocket 订阅链接
至于其他情况，订阅转换服务是第三方提供的，我无法解决相关的问题

**Comment by CocoMilkMaster** [comment]
跳过证书验证 启用  再更新订阅试下
