### ISSUE TITLE
建议加多一条使用动态DNS后，动态DNS（DDNS）冲突的解决办法

### ISSUE THREAD

**Issue by cnwikee** [Aethersailor/Custom_OpenClash_Rules#83]
开启了openclash后，动态DNS获取的公网ip就变成了被fakeip挟持成了本地的IP。
在 openclash →  覆写设置 → DNS设置 → Fake-IP-Filter  ，这个选项里输入放行的网址，然后生效即可

**Comment by Aethersailor** [comment]
已写入 wiki ，感谢提醒。

**Comment by iamdeemo** [comment]
以按照要求添加了放行地址，但群晖后台测试发现还是走了代理，下载速度很慢，然后关了openclash，速度就正常了
