### ISSUE TITLE
大佬能添加一个拳头游戏的直连规则嘛，我发现LOL和瓦还是会走漏网之鱼的节点

### ISSUE THREAD

**Issue by FengNinger** [Aethersailor/Custom_OpenClash_Rules#84]
拳头官网为：www.riotgames.com/

再次感谢大佬

**Comment by ytq77** [comment]
你自己在openclash里面添加就好了，单独把这个域名走直连
两种办法
### 1.在规则附加里面新建一个规则集配置文件
#### 这个方案方便在不用重启openclash就能增加直连的域名
在all里面新建一个配置文件
配置文件选择添加到所有配置文件
别名随便写
规则集类型file
规则类型domain
规则格式text
规则集路径./rule_provider/rule-deirct
规则集匹配顺序优先（覆盖）
指定策略组DIRECT
##### 这时候在管理规则集文件列表里面就能找到自己命名别名的规则，点进去把riotgames.com粘贴进去就好了
然后在yacd或者什么面板的规则里面更新一下你命名的规则他就可以走直连

### 2.复写设置-规则设置，在里面自己添加一条
#### 这个需要重启服务，麻烦一点
加上一条
DOMAIN-SUFFIX,riotgames.com,DIRECT
别忘了格式跟上下的要一致，前面的破折号也一样
然后保存应用配置，等待重启完应该就可以了

**Comment by sun1a2b3c** [comment]
![屏幕截图 2024-11-13 195139](https://github.com/user-attachments/assets/78949bfc-7f09-4957-9b78-2a6b96cc5995)
Openclash中有现成的游戏规则可以用啊
