### ISSUE TITLE
模板文件支持嵌套吗，希望支持高倍率过滤。

### ISSUE THREAD

**Issue by smithereensarr** [Aethersailor/Custom_OpenClash_Rules#86]
custom_clash.ini模板文件可以作为引用，引入到自己的模板文件中，然后通过自定义规则进行覆盖吗？
当前规则中，测速选的最优的节点都是高倍率的，想自己改改，但同时又想实时同步本模板规则集的更新，最好的做法是什么样的呢？

**Comment by Aethersailor** [comment]
fork以后自己修改就行了，按照自己的喜好修改和增删
规则都是引用的上游的，你自己改的模板不需要和本仓库保持一致
