### ISSUE TITLE
自定义规则附加不生效

### ISSUE THREAD

**Issue by ytq77** [Aethersailor/Custom_OpenClash_Rules#91]
![image](https://github.com/user-attachments/assets/8cbefdbd-b4a3-4650-b7bb-e1cd133cf352)
![image](https://github.com/user-attachments/assets/d31f4710-91aa-45cc-b2af-7546f0404df5)
如图所示添加自定义规则并刷新后，依旧无法让指定域名走直连

**Comment by yixuan-ovo** [comment]
![387315591-8cbefdbd-b4a3-4650-b7bb-e1cd133cf352](https://github.com/user-attachments/assets/f56d2636-4d30-431b-b9d1-6edeaccb61e7)
![387315796-d31f4710-91aa-45cc-b2af-7546f0404df5](https://github.com/user-attachments/assets/925b3ec7-2dca-4d84-bd8c-7b41b3c245ff)

**Comment by kiryusento2017** [comment]
你可以直接写在openclash的覆写设置里面

**Comment by ytq77** [comment]
我是想在不重启的情况下实现,不然每次都要覆写有点麻烦

**Comment by kiryusento2017** [comment]
写好一次后面不就可以稳定使用了吗

**Comment by ytq77** [comment]
是这样没错，但是不定时就会发现新的国内域名没有配置，，

**Comment by ytq77** [comment]
已解决,关闭issue
