### ISSUE TITLE
关于pt代理下载的问题

### ISSUE THREAD

**Issue by kiryusento2017** [Aethersailor/Custom_OpenClash_Rules#92]
如果将openclash作为主路由的话，那么就会导致pt代理下载无论怎么样似乎都会走代理，即使已经将tracker加入了附加规则里面让它走直连，但是pt下载本身的原理就是，通过tracker获取目标ip地址，所以这个被获取的ip地址还是会走代理，似乎就是没有办法的，就看看有没有大佬可以帮我看看这个问题

**Comment by Aethersailor** [comment]
没有太好的办法，可以设置只代理80和443端口，但其他情况下又会使用不便
如果平时访问的网站大多是单独策略组包含的，也可以设置漏网之鱼直连

**Comment by kiryusento2017** [comment]
谢谢大佬

**Comment by SysDQ** [comment]
可以把下载客户端的端口绕过代理，这样从这个端口进出的流量都不会经过代理
