### ISSUE TITLE
关于 Google Play 更新一直转圈的问题

### ISSUE THREAD

**Issue by null00001** [Aethersailor/Custom_OpenClash_Rules#93]
- 问题 
使用中碰到 play 商店更新一直转圈的问题。在排查过后，确定是以下两个域名走了不同分流规则后导致的。

`services.googleapis.cn`
`xn--ngstr-lra8j.com`

> 最好是和其他google的域名同一个策略组，如果这俩域名走不同策略组就会导致谷歌play商店更新应用一直等待中、转圈的问题。

<img width="667" alt="Snipaste_2024-11-19_23-03-47" src="https://github.com/user-attachments/assets/b47fcfb4-2dfa-48d2-87a1-ad9e59d54383">

- 解决
尝试在 “绕过指定区域 IPv4 黑名单” 或 “Fake-IP-Filter” 中添加上述域名无法解决，然后尝试在 yaml 文件里面删掉下图中红框以外的规则，让上面两个域名只走"谷歌服务"策略组，得以解决 play 商店更新一直转圈的问题。

![image](https://github.com/user-attachments/assets/448c229e-3840-45dd-90b1-aa0ffbd72bf9)
![image](https://github.com/user-attachments/assets/48af58cc-cea7-403a-8459-43f1bd203574)

- 建议
可否在其他规则组中删除 "googleapis.cn"、"xn--ngstr-lra8j.com" 这俩域名及其子域名，仅在 "谷歌服务" 策略组中保留这两个域名，即可修复此问题。（特别是"Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Direct.list" 中有 "xn--ngstr-lra8j.com" 的直连规则）。

- 其他解决方法
在覆写设置-->自定义规则的优先匹配框中填写以下规则，让俩域名优先匹配  ”谷歌服务“  策略组，也可解决此问题。每个人的地区和设备不一样，有些人play商店更新的域名可能是com后缀，而不是cn，要是出现了类似的问题照抄无法解决，可以按照以上思路排查。

![image](https://github.com/user-attachments/assets/ea7c85e2-9810-474c-8446-cb9a52099db1)

**Comment by kSirZX** [comment]
我也是这样一直转圈······

**Comment by Aethersailor** [comment]
Custom_Direct.list 里的域名是我忘记删了
目前的设置是google play 相关的四条域名默认强制走代理，如果不想走代理就用绕过大陆黑名单功能绕过内核
你更新一下试试看
issue已置顶方便其他人参考

**Comment by kSirZX** [comment]
> Custom_Direct.list 里的域名是我忘记删了 目前的设置是google play 相关的四条域名默认强制走代理，如果不想走代理就用第二 DNS 功能绕过内核 你更新一下试试看 issue已置顶方便其他人参考

更新了还是转圈

**Comment by Aethersailor** [comment]
> > Custom_Direct.list 里的域名是我忘记删了 目前的设置是google play 相关的四条域名默认强制走代理，如果不想走代理就用第二 DNS 功能绕过内核 你更新一下试试看 issue已置顶方便其他人参考
> 
> 更新了还是转圈

services.googleapis.cn
clientservices.googleapis.com
googleapis.cn
xn--ngstr-lra8j.com
以上内容加入绕过大陆黑名单中，ipv4和ipv6都要添加

**Comment by kSirZX** [comment]
> > > Custom_Direct.list 里的域名是我忘记删了 目前的设置是google play 相关的四条域名默认强制走代理，如果不想走代理就用第二 DNS 功能绕过内核 你更新一下试试看 issue已置顶方便其他人参考
> > 
> > 
> > 更新了还是转圈
> 
> services.googleapis.cn clientservices.googleapis.com googleapis.cn xn--ngstr-lra8j.com 以上内容加入绕过大陆黑名单中，ipv4和ipv6都要添加

加了还是转圈呢······

**Comment by null00001** [comment]
> > > > Custom_Direct.list 里的域名是我忘记删了 目前的设置是google play 相关的四条域名默认强制走代理，如果不想走代理就用第二 DNS 功能绕过内核 你更新一下试试看 issue已置顶方便其他人参考
> > > 
> > > 
> > > 更新了还是转圈
> > 
> > 
> > services.googleapis.cn clientservices.googleapis.com googleapis.cn xn--ngstr-lra8j.com 以上内容加入绕过大陆黑名单中，ipv4和ipv6都要添加
> 
> 加了还是转圈呢······

我这边测试是俩域名走同一个节点就行。还不行的话你更新的时候看看openclash的日志，看你更新时相关的是哪些域名，走的哪个代理。自己添加自定义规则，让它们统一走一个节点。注意要清除一下play商店 、google框架的缓存和数据。

**Comment by null00001** [comment]
> Custom_Direct.list 里的域名是我忘记删了 目前的设置是google play 相关的四条域名默认强制走代理，如果不想走代理就用绕过大陆黑名单功能绕过内核 你更新一下试试看 issue已置顶方便其他人参考

这套规则和配置教程是真的不错。我解决play商店更新的问题后使用很完美。感谢作者。

**Comment by ytq77** [comment]
这个是否也可以解决刚打开gmail会提示一段时间无网络连接的问题?

**Comment by taxtigerno1** [comment]
> 这个是否也可以解决刚打开gmail会提示一段时间无网络连接的问题?

我的也是这样，gmail与谷歌商店两个的app使用passwall做翻墙时候都打不开。请问怎么解决

**Comment by SqiChiu** [comment]
用混合模式，然后把ipv4和ipv6黑名单里的google域名都删掉就可以了
